// Code generated by godddx, DO AVOID EDIT.
package sms

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
)

// MediaServerStorer Instantiation interface
type MediaServerStorer interface {
	List(context.Context, *[]*MediaServer, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *MediaServer, ...orm.QueryOption) error
	Create(context.Context, *MediaServer) error
	Update(context.Context, *MediaServer, func(*MediaServer), ...orm.QueryOption) error
	Delete(context.Context, *MediaServer, ...orm.QueryOption) error
}

// ListMediaServers Paginated search
func (c Core) ListMediaServers(ctx context.Context, in *FindMediaServerInput) ([]*MediaServer, int64, error) {
	items := make([]*MediaServer, 0)
	total, err := c.storer.MediaServer().List(ctx, &items, in)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List err[%s]`, err.Error())
	}

	for _, item := range items {
		value, ok := c.cacheServers.Load(item.ID)
		if ok {
			item.Status, _, _ = value.status()
		}
	}
	return items, total, nil
}

// GetMediaServer Query a single object
func (c Core) GetMediaServer(ctx context.Context, id string) (*MediaServer, error) {
	var out MediaServer
	if err := c.storer.MediaServer().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return &out, nil
}

// CreateMediaServer Insert into database
func (c Core) CreateMediaServer(ctx context.Context, in *AddMediaServerInput) (*MediaServer, error) {
	var out MediaServer
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	if err := c.storer.MediaServer().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateMediaServer Update object information
func (c Core) UpdateMediaServer(ctx context.Context, in *EditMediaServerInput, id string, serverPort int) (*MediaServer, error) {
	var out MediaServer
	if err := c.storer.MediaServer().Update(ctx, &out, func(b *MediaServer) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Update err[%s]`, err.Error())
	}
	if err := c.connection(&out, serverPort); err != nil {
		return &out, reason.ErrServer.Withf(`Connect err[%s]`, err.Error())
	}
	return &out, nil
}

// DeleteMediaServer Delete object
func (c Core) DeleteMediaServer(ctx context.Context, id string) (*MediaServer, error) {
	var out MediaServer
	if err := c.storer.MediaServer().Delete(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Delete err[%s]`, err.Error())
	}
	return &out, nil
}

func (c Core) getDefaultMediaServer(ctx context.Context) (*MediaServer, error) {
	var out MediaServer
	return &out, c.storer.MediaServer().Get(ctx, &out, orm.Where("id=?", DefaultMediaServerID))
}

// GetDefaultMediaServer 获取默认流媒体服务器
func (c Core) GetDefaultMediaServer() (*MediaServer, error) {
	return c.getDefaultMediaServer(context.Background())
}
