// Code generated by godddx, DO AVOID EDIT.
package proxydb

import (
	"context"

	"github.com/gowvp/owl/internal/core/proxy"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ proxy.StreamProxyStorer = StreamProxy{}

// StreamProxy Related business namespaces
type StreamProxy DB

// NewStreamProxy instance object
func NewStreamProxy(db *gorm.DB) StreamProxy {
	return StreamProxy{db: db}
}

// List implements proxy.StreamProxyStorer.
func (d StreamProxy) List(ctx context.Context, bs *[]*proxy.StreamProxy, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements proxy.StreamProxyStorer.
func (d StreamProxy) Get(ctx context.Context, model *proxy.StreamProxy, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Create implements proxy.StreamProxyStorer.
func (d StreamProxy) Create(ctx context.Context, model *proxy.StreamProxy) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update implements proxy.StreamProxyStorer.
func (d StreamProxy) Update(ctx context.Context, model *proxy.StreamProxy, changeFn func(*proxy.StreamProxy), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Delete implements proxy.StreamProxyStorer.
func (d StreamProxy) Delete(ctx context.Context, model *proxy.StreamProxy, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

func (d StreamProxy) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

func (d StreamProxy) UpdateWithSession(tx *gorm.DB, model *proxy.StreamProxy, changeFn func(b *proxy.StreamProxy) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
