FROM zlmediakit/zlmediakit:master

ENV TZ=Asia/Shanghai
WORKDIR /opt/media/bin/

# 安全瘦身：删除文档、man、apt 缓存
RUN rm -rf /usr/share/doc/* /usr/share/man/* /var/lib/apt/lists/* /var/cache/apt/*

ARG TARGETARCH
ADD ./build/linux_${TARGETARCH}/bin ./gowvp
ADD ./www ./www

RUN mkdir -p configs


LABEL Name=gowvp \
      Version=0.1.0 \
      Maintainer="xx@golang.space" \
      Description="gowvp & zlmediakit"

EXPOSE 15123 1935 8080 554 20000-20100/udp 20000-20100

CMD ["./gowvp"]
