// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gowvp/owl/internal/conf"
	"github.com/gowvp/owl/internal/core/metadata/metadataapi"
	"github.com/gowvp/owl/internal/data"
	"github.com/gowvp/owl/internal/web/api"
	"github.com/gowvp/owl/pkg/gbs"
	"github.com/ixugo/goddd/domain/version/versionapi"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, log *slog.Logger) (http.Handler, func(), error) {
	db, err := data.SetupDB(bc)
	if err != nil {
		return nil, nil, err
	}
	core := versionapi.NewVersionCore(db)
	versionapiAPI := versionapi.New(core)
	smsCore, cleanup, err := api.NewSMSCore(db, bc)
	if err != nil {
		return nil, nil, err
	}
	smsAPI := api.NewSmsAPI(smsCore)
	storer := api.NewIPCStore(db, bc)
	uniqueidCore := api.NewUniqueID(db)
	adapter := api.NewGBAdapter(storer, uniqueidCore)
	server, cleanup2, err := gbs.NewServer(bc, adapter, smsCore)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ipcBundle := api.NewIPCCoreWithProtocols(storer, uniqueidCore, adapter, smsCore, server, bc)
	recordingStorer := api.NewRecordingStore(db)
	smsProvider := api.NewSMSProviderAdapter(smsCore)
	ipcProvider := api.NewIPCProviderAdapter(ipcBundle)
	playProvider := api.NewPlayProviderAdapter(smsCore)
	recordingCore, cleanup3 := api.NewRecordingCore(recordingStorer, bc, smsProvider, ipcProvider, playProvider)
	dispatcher, cleanup4 := api.NewNotifier(bc)
	eventCore, cleanup5 := api.NewEventCoreWithNotifier(bc, db, dispatcher)
	webHookAPI := api.NewWebHookAPI(smsCore, bc, server, ipcBundle, recordingCore, eventCore)
	ipcapi := api.NewIPCAPI(ipcBundle, recordingCore)
	configAPI := api.NewConfigAPI(db, bc)
	userAPI := api.NewUserAPI(bc)
	aiWebhookAPI := api.NewAIWebhookAPIWithDeps(bc, eventCore, ipcBundle)
	eventAPI := api.NewEventAPI(eventCore, bc)
	recordingAPI := api.NewRecordingAPI(recordingCore, bc)
	metadataCore := metadataapi.NewMetadataCore(db)
	metadataAPI := metadataapi.NewMetadataAPI(metadataCore)
	usecase := &api.Usecase{
		Conf:         bc,
		DB:           db,
		Version:      versionapiAPI,
		SMSAPI:       smsAPI,
		WebHookAPI:   webHookAPI,
		UniqueID:     uniqueidCore,
		GB28181API:   ipcapi,
		ConfigAPI:    configAPI,
		SipServer:    server,
		UserAPI:      userAPI,
		AIWebhookAPI: aiWebhookAPI,
		EventAPI:     eventAPI,
		RecordingAPI: recordingAPI,
		MetadataAPI:  metadataAPI,
	}
	handler := api.NewHTTPHandler(usecase)
	return handler, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
