// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"fmt"
	"strings"
	"sync"

	"github.com/gin-gonic/gin"
	"github.com/gowvp/owl/internal/conf"
	"github.com/gowvp/owl/internal/core/config"
	"github.com/gowvp/owl/internal/core/config/store/configdb"
	"github.com/gowvp/owl/internal/core/ipc"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
	"gorm.io/gorm"
)

type ConfigAPI struct {
	configCore config.Core
	conf       *conf.Bootstrap
	uc         *Usecase
	sipMu      *sync.RWMutex
	sipConfig  *conf.SIP
}

func NewConfigAPI(db *gorm.DB, cfg *conf.Bootstrap) ConfigAPI {
	core := config.NewCore(configdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate()))
	var sipConfig conf.SIP
	if cfg != nil {
		sipConfig = cfg.Sip
	}
	return ConfigAPI{configCore: core, conf: cfg, sipMu: new(sync.RWMutex), sipConfig: &sipConfig}
}

// configIDInput 配置 ID 路径参数
type configIDInput struct {
	ID int `uri:"id" binding:"required"`
}

// updateConfigInput 更新配置的请求参数（路径 ID + 请求体）
type updateConfigInput struct {
	ID int `uri:"id" binding:"required"`
	config.EditConfigInput
}

func registerConfig(g gin.IRouter, api ConfigAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/configs", handler...)
		// group.GET("", web.WrapH(api.listConfigs))
		// group.GET("/:id", web.WrapH(api.getConfig))
		// group.PUT("/:id", web.WrapH(api.updateConfig))
		// group.POST("", web.WrapH(api.createConfig))
		// group.DELETE("/:id", web.WrapH(api.deleteConfig))

		group.GET("/info", web.WrapH(api.getConfigInfo))
		group.PUT("/info/sip", web.WrapH(api.updateSIP))
	}
}

// >>> config >>>>>>>>>>>>>>>>>>>>

func (a ConfigAPI) listConfigs(c *gin.Context, in *config.FindConfigInput) (any, error) {
	items, total, err := a.configCore.ListConfigs(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a ConfigAPI) getConfig(c *gin.Context, in *configIDInput) (any, error) {
	return a.configCore.GetConfig(c.Request.Context(), in.ID)
}

func (a ConfigAPI) updateConfig(c *gin.Context, in *updateConfigInput) (any, error) {
	return a.configCore.UpdateConfig(c.Request.Context(), &in.EditConfigInput, in.ID)
}

func (a ConfigAPI) createConfig(c *gin.Context, in *config.AddConfigInput) (any, error) {
	return a.configCore.CreateConfig(c.Request.Context(), in)
}

func (a ConfigAPI) deleteConfig(c *gin.Context, in *configIDInput) (any, error) {
	return a.configCore.DeleteConfig(c.Request.Context(), in.ID)
}

type getConfigInfoOutput struct {
	SIP        conf.SIP      `json:"sip"`
	AccessInfo SIPAccessInfo `json:"access_info"`
}

type SIPAccessInfo struct {
	ServerIP string `json:"server_ip"`
	ID       string `json:"id"`
	Domain   string `json:"domain"`
	Port     int    `json:"port"`
	Password string `json:"password"`
}

func sipAccessInfo(cfg conf.SIP, fallbackHost string) SIPAccessInfo {
	serverIP := strings.TrimSpace(cfg.Host)
	if serverIP == "" {
		serverIP = strings.TrimSpace(fallbackHost)
	}
	return SIPAccessInfo{
		ServerIP: serverIP,
		ID:       cfg.ID,
		Domain:   cfg.GetDomain(),
		Port:     cfg.Port,
		Password: cfg.Password,
	}
}

type updateSIPInput struct {
	conf.SIP
	DeviceHistory *conf.DeviceHistoryConfig `json:"device_history"`
	SignalDigest  *conf.SIPSignalDigest     `json:"signal_digest"`
	Upstreams     *[]conf.SIPUpstream       `json:"upstreams"`
	Log           *conf.SIPLog              `json:"log"`
}

// getConfigInfo godoc
// @Summary 获取系统配置摘要
// @Tags Config
// @Produce json
// @Security BearerAuth
// @Success 200 {object} SwaggerConfigInfoOutput
// @Failure 400 {object} SwaggerErrorResponse
// @Router /configs/info [get]
func (a ConfigAPI) getConfigInfo(c *gin.Context, _ *struct{}) (*getConfigInfoOutput, error) {
	if a.conf == nil {
		return nil, reason.ErrServer.WithMsg("系统配置不可用")
	}
	if a.sipMu != nil {
		a.sipMu.RLock()
		defer a.sipMu.RUnlock()
	}
	cfg := a.conf.Sip
	if a.sipConfig != nil {
		cfg = *a.sipConfig
	}
	return &getConfigInfoOutput{
		SIP:        cfg,
		AccessInfo: sipAccessInfo(cfg, a.conf.Media.SDPIP),
	}, nil
}

// updateSIP godoc
// @Summary 修改 SIP 配置
// @Tags Config
// @Accept json
// @Produce json
// @Security BearerAuth
// @Param body body SwaggerSIPConfig true "SIP 配置"
// @Success 200 {object} SwaggerMessageResponse
// @Failure 400 {object} SwaggerErrorResponse
// @Router /configs/info/sip [put]
func (a ConfigAPI) updateSIP(_ *gin.Context, in *updateSIPInput) (gin.H, error) {
	if a.conf == nil {
		return nil, reason.ErrServer.WithMsg("系统配置不可用")
	}
	if a.sipMu != nil {
		a.sipMu.Lock()
		defer a.sipMu.Unlock()
	}
	current := a.conf.Sip
	if a.sipConfig != nil {
		current = *a.sipConfig
	}
	next := mergeSIPUpdate(current, in)
	if err := conf.ValidateSIPConfig(next); err != nil {
		return nil, reason.ErrBadRequest.WithMsg(err.Error())
	}
	if fields := sipRestartRequiredFields(current, next); len(fields) > 0 {
		return nil, reason.ErrBadRequest.WithMsg(fmt.Sprintf("修改 %s 后需要重启服务，请修改配置文件并重启", strings.Join(fields, "、")))
	}
	if a.uc != nil && a.uc.SipServer != nil {
		if err := a.uc.SipServer.ValidateCascadeConfig(next); err != nil {
			return nil, reason.ErrBadRequest.WithMsg(err.Error())
		}
	}
	candidate := *a.conf
	candidate.Sip = next
	if err := conf.WriteConfig(&candidate, a.conf.ConfigPath); err != nil {
		return nil, reason.ErrServer.WithMsg(err.Error())
	}
	if a.sipConfig != nil {
		*a.sipConfig = next
	}
	applyHotSIPConfig(&a.conf.Sip, next)
	if a.uc != nil && a.uc.GB28181API.ipc.DeviceHistory() != nil {
		a.uc.GB28181API.ipc.DeviceHistory().SetConfig(ipc.DeviceHistoryConfig{
			MaxRecords: next.DeviceHistory.MaxRecords,
			MaxDays:    next.DeviceHistory.MaxDays,
		})
	}
	if a.uc != nil && a.uc.SipServer != nil {
		a.uc.SipServer.SetConfig(next)
	}

	return gin.H{"msg": "ok"}, nil
}

func applyHotSIPConfig(target *conf.SIP, next conf.SIP) {
	if target == nil {
		return
	}
	// 监听器、平台身份和日志配置已在提交前禁止热更新，这里只同步运行时可安全应用的字段。
	target.Password = next.Password
	target.StrictSourceCheck = next.StrictSourceCheck
	target.RequireMessageAuth = next.RequireMessageAuth
	target.PTZWeakConfirm = next.PTZWeakConfirm
	target.RegisterRedirect = next.RegisterRedirect
	target.SignalDigest = next.SignalDigest
	target.DeviceHistory = next.DeviceHistory
	target.DirectTCPDownload = next.DirectTCPDownload
	target.Upstreams = append([]conf.SIPUpstream(nil), next.Upstreams...)
}

func sipRestartRequiredFields(current, next conf.SIP) []string {
	fields := make([]string, 0, 9)
	if current.Host != next.Host {
		fields = append(fields, "Host")
	}
	if current.ID != next.ID {
		fields = append(fields, "ID")
	}
	if current.GetDomain() != next.GetDomain() {
		fields = append(fields, "Domain")
	}
	if current.Port != next.Port {
		fields = append(fields, "Port")
	}
	if current.EnableTLS != next.EnableTLS {
		fields = append(fields, "EnableTLS")
	}
	if current.TLSPort != next.TLSPort {
		fields = append(fields, "TLSPort")
	}
	if current.TLSCert != next.TLSCert {
		fields = append(fields, "TLSCert")
	}
	if current.TLSKey != next.TLSKey {
		fields = append(fields, "TLSKey")
	}
	if current.Log != next.Log {
		fields = append(fields, "Log")
	}
	return fields
}

func mergeSIPUpdate(current conf.SIP, in *updateSIPInput) conf.SIP {
	if in == nil {
		return current
	}
	next := in.SIP
	if in.DeviceHistory == nil {
		next.DeviceHistory = current.DeviceHistory
	} else {
		next.DeviceHistory = *in.DeviceHistory
	}
	if in.Upstreams == nil {
		next.Upstreams = append([]conf.SIPUpstream(nil), current.Upstreams...)
	} else {
		next.Upstreams = append([]conf.SIPUpstream(nil), (*in.Upstreams)...)
	}
	if in.SignalDigest == nil {
		next.SignalDigest = current.SignalDigest
	} else {
		next.SignalDigest = *in.SignalDigest
	}
	if in.Log == nil {
		next.Log = current.Log
	} else {
		next.Log = *in.Log
	}
	return next
}
