// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/gowvp/owl/internal/conf"
	"github.com/gowvp/owl/internal/core/config"
	"github.com/gowvp/owl/internal/core/config/store/configdb"
	"github.com/gowvp/owl/internal/core/ipc"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

type ConfigAPI struct {
	configCore config.Core
	conf       *conf.Bootstrap
	uc         *Usecase
}

func NewConfigAPI(db *gorm.DB, conf *conf.Bootstrap) ConfigAPI {
	core := config.NewCore(configdb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate()))
	return ConfigAPI{configCore: core, conf: conf}
}

// configIDInput 配置 ID 路径参数
type configIDInput struct {
	ID int `uri:"id" binding:"required"`
}

// updateConfigInput 更新配置的请求参数（路径 ID + 请求体）
type updateConfigInput struct {
	ID int `uri:"id" binding:"required"`
	config.EditConfigInput
}

func registerConfig(g gin.IRouter, api ConfigAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/configs", handler...)
		// group.GET("", web.WrapH(api.listConfigs))
		// group.GET("/:id", web.WrapH(api.getConfig))
		// group.PUT("/:id", web.WrapH(api.updateConfig))
		// group.POST("", web.WrapH(api.createConfig))
		// group.DELETE("/:id", web.WrapH(api.deleteConfig))

		group.GET("/info", web.WrapH(api.getConfigInfo))
		group.PUT("/info/sip", web.WrapH(api.updateSIP))
	}
}

// >>> config >>>>>>>>>>>>>>>>>>>>

func (a ConfigAPI) listConfigs(c *gin.Context, in *config.FindConfigInput) (any, error) {
	items, total, err := a.configCore.ListConfigs(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a ConfigAPI) getConfig(c *gin.Context, in *configIDInput) (any, error) {
	return a.configCore.GetConfig(c.Request.Context(), in.ID)
}

func (a ConfigAPI) updateConfig(c *gin.Context, in *updateConfigInput) (any, error) {
	return a.configCore.UpdateConfig(c.Request.Context(), &in.EditConfigInput, in.ID)
}

func (a ConfigAPI) createConfig(c *gin.Context, in *config.AddConfigInput) (any, error) {
	return a.configCore.CreateConfig(c.Request.Context(), in)
}

func (a ConfigAPI) deleteConfig(c *gin.Context, in *configIDInput) (any, error) {
	return a.configCore.DeleteConfig(c.Request.Context(), in.ID)
}

type getConfigInfoOutput struct {
	SIP        conf.SIP      `json:"sip"`
	AccessInfo SIPAccessInfo `json:"access_info"`
}

type SIPAccessInfo struct {
	ServerIP string `json:"server_ip"`
	ID       string `json:"id"`
	Domain   string `json:"domain"`
	Port     int    `json:"port"`
	Password string `json:"password"`
}

func sipAccessInfo(cfg *conf.Bootstrap) SIPAccessInfo {
	if cfg == nil {
		return SIPAccessInfo{}
	}
	serverIP := strings.TrimSpace(cfg.Sip.Host)
	if serverIP == "" {
		serverIP = strings.TrimSpace(cfg.Media.SDPIP)
	}
	return SIPAccessInfo{
		ServerIP: serverIP,
		ID:       cfg.Sip.ID,
		Domain:   cfg.Sip.GetDomain(),
		Port:     cfg.Sip.Port,
		Password: cfg.Sip.Password,
	}
}

type updateSIPInput struct {
	conf.SIP
	DeviceHistory *conf.DeviceHistoryConfig `json:"device_history"`
	Upstreams     *[]conf.SIPUpstream       `json:"upstreams"`
	Log           *conf.SIPLog              `json:"log"`
}

// getConfigInfo godoc
// @Summary 获取系统配置摘要
// @Tags Config
// @Produce json
// @Security BearerAuth
// @Success 200 {object} SwaggerConfigInfoOutput
// @Failure 400 {object} SwaggerErrorResponse
// @Router /configs/info [get]
func (a ConfigAPI) getConfigInfo(c *gin.Context, _ *struct{}) (*getConfigInfoOutput, error) {
	return &getConfigInfoOutput{
		SIP:        a.conf.Sip,
		AccessInfo: sipAccessInfo(a.conf),
	}, nil
}

// updateSIP godoc
// @Summary 修改 SIP 配置
// @Tags Config
// @Accept json
// @Produce json
// @Security BearerAuth
// @Param body body SwaggerSIPConfig true "SIP 配置"
// @Success 200 {object} SwaggerMessageResponse
// @Failure 400 {object} SwaggerErrorResponse
// @Router /configs/info/sip [put]
func (a ConfigAPI) updateSIP(_ *gin.Context, in *updateSIPInput) (gin.H, error) {
	next := mergeSIPUpdate(a.conf.Sip, in)
	if next.DeviceHistory.MaxRecords < 0 || next.DeviceHistory.MaxRecords > 100000 {
		return nil, reason.ErrBadRequest.WithMsg("设备历史最大记录数应在 0–100000 之间")
	}
	if next.DeviceHistory.MaxDays < 0 || next.DeviceHistory.MaxDays > 3650 {
		return nil, reason.ErrBadRequest.WithMsg("设备历史保留天数应在 0–3650 之间")
	}
	if a.uc != nil && a.uc.SipServer != nil {
		if err := a.uc.SipServer.ValidateCascadeConfig(next); err != nil {
			return nil, reason.ErrBadRequest.WithMsg(err.Error())
		}
	}
	if err := copier.Copy(&a.conf.Sip, &next); err != nil {
		return nil, reason.ErrServer.WithMsg(err.Error())
	}

	if err := conf.WriteConfig(a.conf, a.conf.ConfigPath); err != nil {
		return nil, reason.ErrServer.WithMsg(err.Error())
	}
	if a.uc != nil && a.uc.GB28181API.ipc.DeviceHistory() != nil {
		a.uc.GB28181API.ipc.DeviceHistory().SetConfig(ipc.DeviceHistoryConfig{
			MaxRecords: a.conf.Sip.DeviceHistory.MaxRecords,
			MaxDays:    a.conf.Sip.DeviceHistory.MaxDays,
		})
	}
	if a.uc != nil && a.uc.SipServer != nil {
		a.uc.SipServer.SetConfig()
	}

	return gin.H{"msg": "ok"}, nil
}

func mergeSIPUpdate(current conf.SIP, in *updateSIPInput) conf.SIP {
	if in == nil {
		return current
	}
	next := in.SIP
	if in.DeviceHistory == nil {
		next.DeviceHistory = current.DeviceHistory
	} else {
		next.DeviceHistory = *in.DeviceHistory
	}
	if in.Upstreams == nil {
		next.Upstreams = append([]conf.SIPUpstream(nil), current.Upstreams...)
	} else {
		next.Upstreams = append([]conf.SIPUpstream(nil), (*in.Upstreams)...)
	}
	if in.Log == nil {
		next.Log = current.Log
	} else {
		next.Log = *in.Log
	}
	return next
}
