// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/gowvp/owl/internal/adapter/onvifadapter"
	"github.com/gowvp/owl/internal/core/bz"
	"github.com/gowvp/owl/internal/core/ipc"
	"github.com/gowvp/owl/internal/core/recording"
	"github.com/gowvp/owl/internal/core/sms"
	"github.com/gowvp/owl/pkg/zlm"
	"github.com/ixugo/goddd/pkg/hook"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
)

var ErrDevice = reason.NewError("ErrDevice", "设备错误")

const (
	coverDir = "cover"
)

// TODO: 快照不会删除，只会覆盖，设备删除时也不会删除快照，待实现
func writeCover(dataDir, channelID string, body []byte) error {
	coverPath := filepath.Join(dataDir, coverDir)
	if err := os.MkdirAll(coverPath, 0o777); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(coverPath, channelID+".jpg"), body, 0o644)
}

func readCoverPath(dataDir, channelID string) string {
	coverPath := filepath.Join(dataDir, coverDir)
	return filepath.Join(coverPath, channelID+".jpg")
}

func readCover(dataDir, channelID string) ([]byte, error) {
	return os.ReadFile(readCoverPath(dataDir, channelID))
}

type IPCAPI struct {
	ipc           ipc.Core
	uc            *Usecase
	recordingCore recording.Core
}

func NewIPCAPI(bundle IPCBundle, recordingCore recording.Core) IPCAPI {
	return IPCAPI{ipc: bundle.Core, recordingCore: recordingCore}
}

func registerGB28181(g gin.IRouter, api IPCAPI, handler ...gin.HandlerFunc) {
	// GB28181 协议特有的回调接口
	g.Any("/gb28181/snapshot", func(c *gin.Context) {
		b, err := io.ReadAll(c.Request.Body)
		if err != nil {
			panic(err)
		}
		channelID := strings.TrimSpace(c.Query("channel_id"))
		if channelID == "" {
			// 兼容设备不回传 channel_id 的场景，退化到 device_id 作为快照主键。
			channelID = strings.TrimSpace(c.Query("device_id"))
		}
		if channelID == "" {
			channelID = orm.GenerateRandomString(10)
		}
		if len(b) > 0 {
			if err := writeCover(api.uc.Conf.ConfigDir, channelID, b); err != nil {
				slog.ErrorContext(c.Request.Context(), "write cover", "err", err, "channel_id", channelID)
			}
		}
		c.JSON(200, gin.H{"msg": "ok"})
	})

	// 统一的设备管理 API（支持所有协议）
	{
		group := g.Group("/devices", handler...)
		group.GET("", web.WrapH(api.findDevice))                     // 设备列表（所有协议）
		group.GET("/:id", web.WrapH(api.getDevice))                  // 设备详情（所有协议）
		group.PUT("/:id", web.WrapH(api.editDevice))                 // 修改设备（所有协议）
		group.POST("", web.WrapH(api.addDevice))                     // 添加设备（所有协议，通过 type 区分）
		group.DELETE("/:id", web.WrapH(api.delDevice))               // 删除设备（所有协议）
		group.GET("/channels", web.WrapH(api.FindChannelsForDevice)) // 设备与通道列表（所有协议）
		group.POST("/:id/catalog", web.WrapH(api.queryCatalog))
		group.POST("/:id/gb/control", web.WrapH(api.gbDeviceControl)) // GB 附录A.2.3 设备控制
		group.POST("/:id/gb/query", web.WrapH(api.gbDeviceQuery))     // GB 附录A.2.4 设备查询
		group.GET("/:id/gb/a4_snapshot", web.WrapH(api.gbAppendixA4Snapshot))
	}
	{
		// group := g.Group("/onvif", handler...)
		g.GET("/onvif/discover", api.discover) // ONVIF 设备发现（ONVIF 特有）
		// group.GET("/discover", api.discover)   // ONVIF 设备发现（ONVIF 特有）
	}

	// 统一的通道管理 API（支持所有协议）
	{
		group := g.Group("/channels", handler...)
		group.GET("", web.WrapH(api.findChannel))                     // 通道列表（所有协议）
		group.POST("", web.WrapH(api.addChannel))                     // 添加通道（RTMP/RTSP）
		group.PUT("/:id", web.WrapH(api.editChannel))                 // 修改通道（所有协议）
		group.DELETE("/:id", web.WrapH(api.delChannel))               // 删除通道（RTMP/RTSP）
		group.POST("/:id/play", web.WrapH(api.play))                  // 播放（所有协议）
		group.POST("/:id/records/query", web.WrapH(api.queryRecords)) // 录像目录查询（GB28181）
		group.POST("/:id/ptz", web.WrapH(api.ptzControl))             // 云台控制（GB28181/ONVIF）
		group.POST("/:id/upgrade", web.WrapH(api.upgradeDevice))      // 设备升级（GB28181-2022）
		group.POST("/:id/history/start", web.WrapH(api.startHistory)) // 历史回放/下载开始（GB28181）
		group.POST("/:id/history/stop", web.WrapH(api.stopHistory))   // 历史回放/下载停止（GB28181）
		group.POST("/:id/history/control", web.WrapH(api.controlHistory))
		group.POST("/:id/voice/start", web.WrapH(api.startVoice))    // 语音对讲/广播开始（GB28181）
		group.POST("/:id/voice/stop", web.WrapH(api.stopVoice))      // 语音对讲/广播停止（GB28181）
		group.POST("/:id/snapshot", web.WrapH(api.refreshSnapshot))  // 图像抓拍（所有协议）
		group.GET("/:id/snapshot", api.getSnapshot)                  // 获取图像（所有协议）
		group.POST("/:id/zones", web.WrapH(api.addZone))             // 添加区域（所有协议）
		group.GET("/:id/zones", web.WrapH(api.getZones))             // 获取区域（所有协议）
		group.POST("/:id/ai/enable", web.WrapH(api.enableAI))        // 启用 AI 检测
		group.POST("/:id/ai/disable", web.WrapH(api.disableAI))      // 禁用 AI 检测
		group.POST("/:id/record_mode", web.WrapH(api.setRecordMode)) // 设置录像模式
	}
	{
		group := g.Group("/devices", handler...)
		group.POST("/:id/time_sync", web.WrapH(api.syncTime))  // 校时（GB28181）
		group.POST("/:id/subscribe", web.WrapH(api.subscribe)) // 订阅（GB28181）
		group.POST("/:id/options_probe", web.WrapH(api.optionsProbe))
	}
}

// >>> device >>>>>>>>>>>>>>>>>>>>

func (a IPCAPI) findDevice(c *gin.Context, in *ipc.FindDeviceInput) (any, error) {
	items, total, err := a.ipc.FindDevice(c.Request.Context(), in)
	fillDeviceRecordMode(items)
	return gin.H{"items": items, "total": total}, err
}

func (a IPCAPI) getDevice(c *gin.Context, _ *struct{}) (any, error) {
	deviceID := c.Param("id")
	dev, err := a.ipc.GetDevice(c.Request.Context(), deviceID)
	if err != nil {
		return nil, err
	}
	fillDeviceRecordMode([]*ipc.Device{dev})
	return dev, nil
}

func (a IPCAPI) editDevice(c *gin.Context, in *ipc.EditDeviceInput) (any, error) {
	deviceID := c.Param("id")
	return a.ipc.EditDevice(c.Request.Context(), in, deviceID)
}

// addDevice 添加设备（支持所有协议类型）
// 通过 type 字段区分协议: "GB28181" 或 "ONVIF"
//
// 示例1 - 添加 GB28181 设备:
//
//	POST /devices
//	{ "type": "GB28181", "device_id": "34020000001320000001", "name": "摄像头1" }
//
// 示例2 - 添加 ONVIF 设备:
//
//	POST /devices
//	{ "type": "ONVIF", "ip": "192.168.1.100", "port": 80, "username": "admin", "password": "12345" }
func (a IPCAPI) addDevice(c *gin.Context, in *ipc.AddDeviceInput) (any, error) {
	in.Type = strings.ToUpper(in.Type)
	if !slices.Contains([]string{ipc.TypeGB28181, ipc.TypeOnvif}, in.Type) {
		return nil, reason.ErrBadRequest.SetMsg("不支持的设备类型")
	}
	return a.ipc.AddDevice(c.Request.Context(), in)
}

func (a IPCAPI) delDevice(c *gin.Context, _ *struct{}) (any, error) {
	did := c.Param("id")
	return a.ipc.DelDevice(c.Request.Context(), did)
}

func (a IPCAPI) queryCatalog(c *gin.Context, _ *struct{}) (any, error) {
	did := c.Param("id")

	if err := a.ipc.QueryCatalog(c.Request.Context(), did); err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}

	return gin.H{"msg": "ok"}, nil
}

func (a IPCAPI) FindChannelsForDevice(c *gin.Context, in *ipc.FindDeviceInput) (any, error) {
	ctx := c.Request.Context()
	items, total, err := a.ipc.FindChannelsForDevice(ctx, in)
	fillDeviceRecordMode(items)

	// 收集所有通道 ID 用于批量查询录像
	var cids []string
	for _, dev := range items {
		for _, ch := range dev.Children {
			cids = append(cids, ch.ID)
		}
	}

	// 批量查询哪些通道有录像
	hasRecordingMap, _ := a.recordingCore.HasRecordings(ctx, cids)

	// 为每个通道设置 has_recording 标记
	for _, dev := range items {
		for _, ch := range dev.Children {
			ch.HasRecording = hasRecordingMap[ch.ID]
		}
	}

	// 按照在线优先排序
	sort.SliceStable(items, func(i, j int) bool {
		return items[i].IsOnline && !items[j].IsOnline
	})
	// 按照第 1 个通道是否在线排序
	sort.SliceStable(items, func(i, j int) bool {
		if len(items[i].Children) > 0 && len(items[j].Children) > 0 {
			return items[i].Children[0].IsOnline && !items[j].Children[0].IsOnline
		}
		return false
	})

	return gin.H{"items": items, "total": total}, err
}

// fillDeviceRecordMode 统一设备接口返回：record_mode 为空时回填默认值。
func fillDeviceRecordMode(items []*ipc.Device) {
	for _, dev := range items {
		if dev == nil {
			continue
		}
		dev.Ext.RecordMode = dev.Ext.GetRecordMode()
		for _, ch := range dev.Children {
			if ch == nil {
				continue
			}
			ch.Ext.RecordMode = ch.Ext.GetRecordMode()
		}
	}
}

// >>> channel >>>>>>>>>>>>>>>>>>>>

func (a IPCAPI) findChannel(c *gin.Context, in *ipc.FindChannelInput) (any, error) {
	items, total, err := a.ipc.FindChannel(c.Request.Context(), in)
	if err != nil {
		return nil, err
	}

	// 为 RTMP 类型通道生成推流地址
	a.fillRTMPPushAddr(c, items)

	return gin.H{"items": items, "total": total}, nil
}

// fillRTMPPushAddr 为 RTMP 类型通道填充推流地址
func (a IPCAPI) fillRTMPPushAddr(c *gin.Context, items []*ipc.Channel) {
	if a.uc == nil {
		return
	}

	// 获取流媒体服务器配置
	ms, err := a.uc.SMSAPI.smsCore.GetMediaServer(c.Request.Context(), sms.DefaultMediaServerID)
	if err != nil {
		return
	}

	host := web.GetHost(c.Request)

	rtmpPort := ms.Ports.RTMP
	if rtmpPort == 0 {
		rtmpPort = 1935 // 默认 RTMP 端口
	}

	sign := hook.MD5(a.uc.Conf.Server.RTMPSecret)

	for _, item := range items {
		if item.IsRTMP() {
			item.Config.PushAddr = fmt.Sprintf("rtmp://%s:%d/%s/%s", host, rtmpPort, item.App, item.Stream)
			if !item.Config.IsAuthDisabled {
				item.Config.PushAddr += "?sign=" + sign
			}
		}
	}
}

// func (a GB28181API) getChannel(c *gin.Context, _ *struct{}) (any, error) {
// 	channelID := c.Param("id")
// 	return a.gb28181Core.GetChannel(c.Request.Context(), channelID)
// }

func (a IPCAPI) editChannel(c *gin.Context, in *ipc.EditChannelInput) (any, error) {
	cid := c.Param("id")
	return a.ipc.EditChannel(c.Request.Context(), in, cid)
}

// addChannel 添加 RTMP/RTSP 通道
func (a IPCAPI) addChannel(c *gin.Context, in *ipc.AddChannelInput) (any, error) {
	in.Type = strings.ToUpper(in.Type)
	if !slices.Contains([]string{ipc.TypeRTMP, ipc.TypeRTSP}, in.Type) {
		return nil, reason.ErrBadRequest.SetMsg("仅支持 RTMP/RTSP 类型通道")
	}
	return a.ipc.AddChannel(c.Request.Context(), in)
}

// delChannel 删除 RTMP/RTSP 通道
func (a IPCAPI) delChannel(c *gin.Context, _ *struct{}) (any, error) {
	channelID := c.Param("id")

	// 仅允许删除 RTMP/RTSP 类型通道
	if !bz.IsRTMP(channelID) && !bz.IsRTSP(channelID) {
		return nil, reason.ErrBadRequest.SetMsg("仅支持删除 RTMP/RTSP 类型通道")
	}

	return a.ipc.DelChannel(c.Request.Context(), channelID)
}

func (a IPCAPI) play(c *gin.Context, _ *struct{}) (*playOutput, error) {
	channelID := c.Param("id")

	var app, appStream, host, stream, session, mediaServerID string

	// 国标逻辑
	if bz.IsGB28181(channelID) {
		// 防止错误的配置，无法收到流
		if a.uc.Conf.Media.SDPIP == "127.0.0.1" {
			return nil, reason.ErrUsedLogic.SetMsg("请先配置流媒体 SDP 收流地址")
		}
		ch, err := a.ipc.GetChannel(c.Request.Context(), channelID)
		if err != nil {
			return nil, err
		}

		app = "rtp"
		appStream = ch.ID
		mediaServerID = sms.DefaultMediaServerID

	} else if bz.IsRTMP(channelID) {
		// 从 Channel 获取 RTMP 推流信息
		ch, err := a.ipc.GetChannel(c.Request.Context(), channelID)
		if err != nil {
			return nil, err
		}
		if !ch.IsOnline {
			return nil, reason.ErrNotFound.SetMsg("未推流")
		}
		app = ch.App
		appStream = ch.Stream
		mediaServerID = ch.Config.MediaServerID
		if mediaServerID == "" {
			mediaServerID = sms.DefaultMediaServerID
		}

		if !ch.Config.IsAuthDisabled && ch.Config.Session != "" {
			session = "session=" + ch.Config.Session
		}
	} else if bz.IsRTSP(channelID) {
		// 从 Channel 获取 RTSP 拉流代理信息
		ch, err := a.ipc.GetChannel(c.Request.Context(), channelID)
		if err != nil {
			return nil, err
		}
		app = ch.App
		if app == "" {
			app = "live"
		}
		appStream = ch.Stream
		mediaServerID = ch.Config.MediaServerID
		if mediaServerID == "" {
			mediaServerID = sms.DefaultMediaServerID
		}
	} else if bz.IsOnvif(channelID) {
		app = "live"
		appStream = channelID
		mediaServerID = sms.DefaultMediaServerID
	} else {
		return nil, reason.ErrNotFound.SetMsg("不支持的播放通道")
	}

	if !a.uc.SMSAPI.smsCore.IsOnline(mediaServerID) {
		return nil, reason.ErrNotFound.SetMsg("Oops! 流媒体服务离线或IP有误")
	}
	svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(c.Request.Context(), mediaServerID)
	if err != nil {
		return nil, err
	}

	stream = app + "/" + appStream

	host = c.Request.Host
	if l := strings.Split(c.Request.Host, ":"); len(l) == 2 {
		host = l[0]
	}
	httpPort := a.uc.Conf.Server.HTTP.Port

	// 播放规则
	// https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99
	prefix := c.Request.Header.Get("X-Forwarded-Prefix")
	if prefix == "" {
		prefix = "http://" + host + ":" + strconv.Itoa(httpPort)
	}
	if h := c.Request.Header.Get("X-Forwarded-Host"); h != "" {
		host = h
	}

	item := a.uc.SMSAPI.smsCore.GetStreamLiveAddr(svr, prefix, host, app, appStream)
	out := playOutput{
		App:    app,
		Stream: appStream,
		Items:  []sms.StreamLiveAddr{item},
	}

	// 取一张快照
	go func() {
		rtsp := fmt.Sprintf("rtsp://%s:%d/%s", "127.0.0.1", svr.Ports.RTSP, stream) + "?" + session
		for range 2 {
			time.Sleep(3 * time.Second)

			body, err := a.uc.SMSAPI.smsCore.GetSnapshot(svr, sms.GetSnapRequest{
				GetSnapRequest: zlm.GetSnapRequest{
					URL:        rtsp,
					TimeoutSec: 10,
					ExpireSec:  15,
				},
				Stream: channelID,
			})
			if err != nil {
				slog.ErrorContext(c.Request.Context(), "get snapshot", "err", err)
				continue
			}
			if err := writeCover(a.uc.Conf.ConfigDir, channelID, body); err != nil {
				slog.ErrorContext(c.Request.Context(), "write cover", "err", err)
			}
			break
		}
		// if a.uc.Conf.Server.AI.Disabled || a.uc.AIWebhookAPI.ai == nil {
		// 	return
		// }

		// if _, ok := a.uc.AIWebhookAPI.aiTasks.LoadOrStore(channelID, struct{}{}); !ok {
		// 	resp, err := a.uc.AIWebhookAPI.ai.StartCamera(context.Background(), &protos.StartCameraRequest{
		// 		CameraId:       appStream,
		// 		CameraName:     appStream,
		// 		RtspUrl:        rtsp,
		// 		DetectFps:      5,
		// 		Labels:         []string{"person", "car", "cat", "dog"},
		// 		Threshold:      0.65,
		// 		RetryLimit:     10,
		// 		CallbackUrl:    fmt.Sprintf("http://127.0.0.1:%d/ai", a.uc.Conf.Server.HTTP.Port),
		// 		CallbackSecret: "Basic 1234567890",
		// 	})
		// 	if err != nil {
		// 		slog.Error("start camera", "err", err)
		// 		return
		// 	}
		// 	slog.Debug("start camera", "resp", resp,
		// 		"msg", resp.GetMessage(),
		// 		"source_width", resp.GetSourceWidth(),
		// 		"source_height", resp.GetSourceHeight(),
		// 		"source_fps", resp.GetSourceFps(),
		// 	)
		// }
	}()
	return &out, nil
}

type refreshSnapshotInput struct {
	// 指定获取多少秒内创建的快照
	WithinSeconds int64 `json:"within_seconds"`
	// 取快照的链接地址
	URL string `json:"url"`
}

type ptzControlInput struct {
	Action  string `json:"action"`
	Speed   uint8  `json:"speed"`
	Timeout int    `json:"timeout"` // seconds
	Preset  int    `json:"preset"`
	Group   uint8  `json:"group"`
	Aux     uint8  `json:"aux"`
	Value   uint16 `json:"value"`
}

type queryRecordsInput struct {
	StartAt int64 `json:"start_at"` // unix 秒
	EndAt   int64 `json:"end_at"`   // unix 秒
	Timeout int   `json:"timeout"`  // seconds
}

type upgradeDeviceInput struct {
	Firmware     string `json:"firmware"`
	FileURL      string `json:"file_url"`
	Manufacturer string `json:"manufacturer"`
	SessionID    string `json:"session_id"`
	Timeout      int    `json:"timeout"` // seconds
}

type historyControlInput struct {
	Mode    string  `json:"mode"` // playback/download
	StartAt int64   `json:"start_at"`
	EndAt   int64   `json:"end_at"`
	Cmd     string  `json:"cmd"`
	Action  string  `json:"action"`
	Scale   float64 `json:"scale"`
	SeekAt  int64   `json:"seek_at"`
}

type voiceControlInput struct {
	Mode string `json:"mode"` // talk/broadcast
}

type subscribeInput struct {
	Event   string `json:"event"`
	Expires int    `json:"expires"`
}

type optionsProbeInput struct {
	Timeout int `json:"timeout"`
}

type gbDragZoomInput struct {
	Length    int `json:"length"`
	Width     int `json:"width"`
	MidPointX int `json:"mid_point_x"`
	MidPointY int `json:"mid_point_y"`
	LengthX   int `json:"length_x"`
	LengthY   int `json:"length_y"`
}

type gbHomePositionInput struct {
	Enabled     *int `json:"enabled"`
	ResetTime   *int `json:"reset_time"`
	PresetIndex *int `json:"preset_index"`
}

type gbPTZPreciseInput struct {
	Pan  *float64 `json:"pan"`
	Tilt *float64 `json:"tilt"`
	Zoom *float64 `json:"zoom"`
}

type gbPTZCmdParamInput struct {
	PresetName      string `json:"preset_name"`
	CruiseTrackName string `json:"cruise_track_name"`
}

type gbDeviceControlInput struct {
	TargetID     string               `json:"target_id"`
	Action       string               `json:"action"`
	Timeout      int                  `json:"timeout"`
	PTZCmd       string               `json:"ptz_cmd"`
	PTZCmdParam  *gbPTZCmdParamInput  `json:"ptz_cmd_param"`
	StreamNumber int                  `json:"stream_number"`
	AlarmMethod  string               `json:"alarm_method"`
	AlarmType    string               `json:"alarm_type"`
	DragZoom     *gbDragZoomInput     `json:"drag_zoom"`
	HomePosition *gbHomePositionInput `json:"home_position"`
	PTZPrecise   *gbPTZPreciseInput   `json:"ptz_precise"`
	SDCardID     int                  `json:"sdcard_id"`
}

type gbDeviceQueryInput struct {
	TargetID   string `json:"target_id"`
	Action     string `json:"action"`
	Timeout    int    `json:"timeout"`
	ConfigType string `json:"config_type"`
	Interval   int    `json:"interval"`
	Start      int64  `json:"start"`
	End        int64  `json:"end"`
}

// gbAppendixA4SnapshotInput 为附录 A.4 快照查询参数。
type gbAppendixA4SnapshotInput struct {
	CmdType string `form:"cmd_type" json:"cmd_type"`
	Limit   int    `form:"limit" json:"limit"`
}

// gbAppendixA4Output 是附录 A.4 扩展对象 API 出参模型。
type gbAppendixA4Output struct {
	Type      string            `json:"type"`
	CmdType   string            `json:"cmd_type,omitempty"`
	Path      string            `json:"path,omitempty"`
	Fields    map[string]string `json:"fields,omitempty"`
	RawXML    string            `json:"raw_xml,omitempty"`
	UpdatedAt int64             `json:"updated_at,omitempty"`
}

// gbDeviceQueryOutput 是 GB 附录 A.2.4 查询 API 出参模型。
// 说明：appendix_a4 字段用于承接附录 A.4 扩展对象结构化结果。
type gbDeviceQueryOutput struct {
	SN         int                  `json:"sn"`
	CmdType    string               `json:"cmd_type"`
	DeviceID   string               `json:"device_id"`
	Result     string               `json:"result,omitempty"`
	XML        string               `json:"xml"`
	Data       any                  `json:"data,omitempty"`
	AppendixA4 []gbAppendixA4Output `json:"appendix_a4,omitempty"`
}

// gbAppendixA4SnapshotOutput 为附录 A.4 快照查询 API 出参模型。
type gbAppendixA4SnapshotOutput struct {
	DeviceID string               `json:"device_id"`
	Filter   string               `json:"filter,omitempty"`
	Total    int                  `json:"total"`
	Items    []gbAppendixA4Output `json:"items"`
}

// queryRecords 查询通道录像目录（当前由 GB28181 协议实现）。
func (a IPCAPI) queryRecords(c *gin.Context, in *queryRecordsInput) (any, error) {
	channelID := c.Param("id")
	out, err := a.ipc.QueryRecords(c.Request.Context(), channelID, &ipc.RecordQueryInput{
		StartAt: in.StartAt,
		EndAt:   in.EndAt,
		Timeout: in.Timeout,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return out, nil
}

// upgradeDevice 执行设备软件升级（GB/T 28181-2022 9.13）。
// 若设备协议版本低于 2022，返回“协议不支持”。
func (a IPCAPI) upgradeDevice(c *gin.Context, in *upgradeDeviceInput) (any, error) {
	channelID := c.Param("id")
	err := a.ipc.UpgradeDevice(c.Request.Context(), channelID, &ipc.UpgradeInput{
		Firmware:     in.Firmware,
		FileURL:      in.FileURL,
		Manufacturer: in.Manufacturer,
		SessionID:    in.SessionID,
		Timeout:      in.Timeout,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// startHistory 启动历史回放/下载会话。
func (a IPCAPI) startHistory(c *gin.Context, in *historyControlInput) (any, error) {
	channelID := c.Param("id")
	err := a.ipc.StartHistory(c.Request.Context(), channelID, &ipc.HistoryControlInput{
		Mode:    in.Mode,
		StartAt: in.StartAt,
		EndAt:   in.EndAt,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// stopHistory 停止历史回放/下载会话。
func (a IPCAPI) stopHistory(c *gin.Context, in *historyControlInput) (any, error) {
	channelID := c.Param("id")
	err := a.ipc.StopHistory(c.Request.Context(), channelID, &ipc.HistoryControlInput{
		Mode: in.Mode,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// controlHistory 下发历史回放/下载控制命令（INFO/MANSRTSP）。
func (a IPCAPI) controlHistory(c *gin.Context, in *historyControlInput) (any, error) {
	channelID := c.Param("id")
	err := a.ipc.ControlHistory(c.Request.Context(), channelID, &ipc.HistoryControlInput{
		Mode:   in.Mode,
		Cmd:    in.Cmd,
		Action: in.Action,
		Scale:  in.Scale,
		SeekAt: in.SeekAt,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// startVoice 启动语音会话（对讲/广播）。
func (a IPCAPI) startVoice(c *gin.Context, in *voiceControlInput) (any, error) {
	channelID := c.Param("id")
	err := a.ipc.StartVoice(c.Request.Context(), channelID, &ipc.VoiceControlInput{
		Mode: in.Mode,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// stopVoice 停止语音会话（对讲/广播）。
func (a IPCAPI) stopVoice(c *gin.Context, in *voiceControlInput) (any, error) {
	channelID := c.Param("id")
	err := a.ipc.StopVoice(c.Request.Context(), channelID, &ipc.VoiceControlInput{
		Mode: in.Mode,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// syncTime 执行设备校时。
func (a IPCAPI) syncTime(c *gin.Context, _ *struct{}) (any, error) {
	deviceID := c.Param("id")
	if err := a.ipc.SyncTime(c.Request.Context(), deviceID); err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// subscribe 发起事件订阅。
func (a IPCAPI) subscribe(c *gin.Context, in *subscribeInput) (any, error) {
	deviceID := c.Param("id")
	if err := a.ipc.Subscribe(c.Request.Context(), deviceID, &ipc.SubscribeInput{
		Event:   in.Event,
		Expires: in.Expires,
	}); err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// optionsProbe 发起设备 OPTIONS 探测。
func (a IPCAPI) optionsProbe(c *gin.Context, in *optionsProbeInput) (any, error) {
	deviceID := c.Param("id")
	if err := a.ipc.ProbeOptions(c.Request.Context(), deviceID, &ipc.OptionsProbeInput{
		Timeout: in.Timeout,
	}); err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

// gbDeviceControl 执行 GB 附录 A.2.3 统一设备控制命令。
func (a IPCAPI) gbDeviceControl(c *gin.Context, in *gbDeviceControlInput) (any, error) {
	deviceID := c.Param("id")
	out, err := a.ipc.GBDeviceControl(c.Request.Context(), deviceID, &ipc.GBDeviceControlInput{
		TargetID:     in.TargetID,
		Action:       in.Action,
		Timeout:      in.Timeout,
		PTZCmd:       in.PTZCmd,
		PTZCmdParam:  toIPCPTZCmdParam(in.PTZCmdParam),
		StreamNumber: in.StreamNumber,
		AlarmMethod:  in.AlarmMethod,
		AlarmType:    in.AlarmType,
		SDCardID:     in.SDCardID,
		DragZoom:     toIPCDragZoom(in.DragZoom),
		HomePosition: toIPCHomePosition(in.HomePosition),
		PTZPrecise:   toIPCPTZPrecise(in.PTZPrecise),
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return out, nil
}

// gbDeviceQuery 执行 GB 附录 A.2.4 统一设备查询命令。
func (a IPCAPI) gbDeviceQuery(c *gin.Context, in *gbDeviceQueryInput) (any, error) {
	deviceID := c.Param("id")
	out, err := a.ipc.GBDeviceQuery(c.Request.Context(), deviceID, &ipc.GBDeviceQueryInput{
		TargetID:   in.TargetID,
		Action:     in.Action,
		Timeout:    in.Timeout,
		ConfigType: in.ConfigType,
		Interval:   in.Interval,
		Start:      in.Start,
		End:        in.End,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	resp := gbDeviceQueryOutput{
		SN:         out.SN,
		CmdType:    out.CmdType,
		DeviceID:   out.DeviceID,
		Result:     out.Result,
		XML:        out.XML,
		Data:       out.Data,
		AppendixA4: make([]gbAppendixA4Output, 0, len(out.AppendixA4)),
	}
	for _, item := range out.AppendixA4 {
		resp.AppendixA4 = append(resp.AppendixA4, gbAppendixA4Output{
			Type:      item.Type,
			CmdType:   item.CmdType,
			Path:      item.Path,
			Fields:    item.Fields,
			RawXML:    item.RawXML,
			UpdatedAt: item.UpdatedAt,
		})
	}
	return resp, nil
}

// gbAppendixA4Snapshot 查询已落库的附录 A.4 快照（只读）。
// 支持按 cmd_type 过滤，cmd_type 可传逗号分隔多值。
func (a IPCAPI) gbAppendixA4Snapshot(c *gin.Context, in *gbAppendixA4SnapshotInput) (any, error) {
	deviceID := c.Param("id")
	out, err := a.ipc.GBAppendixA4Snapshot(c.Request.Context(), deviceID, &ipc.GBAppendixA4SnapshotInput{
		CmdType: in.CmdType,
		Limit:   in.Limit,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	resp := gbAppendixA4SnapshotOutput{
		DeviceID: out.DeviceID,
		Filter:   out.Filter,
		Total:    out.Total,
		Items:    make([]gbAppendixA4Output, 0, len(out.Items)),
	}
	for _, item := range out.Items {
		resp.Items = append(resp.Items, gbAppendixA4Output{
			Type:      item.Type,
			CmdType:   item.CmdType,
			Path:      item.Path,
			Fields:    item.Fields,
			RawXML:    item.RawXML,
			UpdatedAt: item.UpdatedAt,
		})
	}
	return resp, nil
}

func toIPCDragZoom(in *gbDragZoomInput) *ipc.GBDragZoomInput {
	if in == nil {
		return nil
	}
	return &ipc.GBDragZoomInput{
		Length:    in.Length,
		Width:     in.Width,
		MidPointX: in.MidPointX,
		MidPointY: in.MidPointY,
		LengthX:   in.LengthX,
		LengthY:   in.LengthY,
	}
}

func toIPCHomePosition(in *gbHomePositionInput) *ipc.GBHomePositionInput {
	if in == nil {
		return nil
	}
	return &ipc.GBHomePositionInput{
		Enabled:     in.Enabled,
		ResetTime:   in.ResetTime,
		PresetIndex: in.PresetIndex,
	}
}

func toIPCPTZPrecise(in *gbPTZPreciseInput) *ipc.GBPTZPreciseInput {
	if in == nil {
		return nil
	}
	return &ipc.GBPTZPreciseInput{
		Pan:  in.Pan,
		Tilt: in.Tilt,
		Zoom: in.Zoom,
	}
}

func toIPCPTZCmdParam(in *gbPTZCmdParamInput) *ipc.GBPTZCmdParamInput {
	if in == nil {
		return nil
	}
	return &ipc.GBPTZCmdParamInput{
		PresetName:      in.PresetName,
		CruiseTrackName: in.CruiseTrackName,
	}
}

func (a IPCAPI) ptzControl(c *gin.Context, in *ptzControlInput) (any, error) {
	channelID := c.Param("id")
	err := a.ipc.PTZControl(c.Request.Context(), channelID, &ipc.PTZControlInput{
		Action:  in.Action,
		Speed:   in.Speed,
		Timeout: in.Timeout,
		Preset:  in.Preset,
		Group:   in.Group,
		Aux:     in.Aux,
		Value:   in.Value,
	})
	if err != nil {
		return nil, ErrDevice.SetMsg(err.Error())
	}
	return gin.H{"msg": "ok"}, nil
}

func (a IPCAPI) refreshSnapshot(c *gin.Context, in *refreshSnapshotInput) (any, error) {
	channelID := c.Param("id")

	path := readCoverPath(a.uc.Conf.ConfigDir, channelID)

	token := c.GetString("token")

	prefix := web.GetBaseURL(c.Request)
	if v := c.Request.Header.Get("X-Forwarded-Prefix"); v != "" {
		prefix = v
	}

	// 获取文件的修改时间
	fileInfo, err := os.Stat(path)
	if err == nil {
		if fileInfo.ModTime().Unix() > time.Now().Unix()-in.WithinSeconds {
			return gin.H{"link": fmt.Sprintf("%s/channels/%s/snapshot?token=%s", prefix, channelID, token)}, nil
		}
	}

	if bz.IsGB28181(channelID) {
		// GB28181 优先走 9.14 抓拍流程，由设备回传图片到 /gb28181/snapshot。
		ch, err := a.ipc.GetChannel(c.Request.Context(), channelID)
		if err != nil {
			return nil, err
		}
		if _, err = a.ipc.GetDevice(c.Request.Context(), ch.DID); err != nil {
			return nil, err
		}
		if err := a.uc.SipServer.QuerySnapshot(ch.DeviceID, ch.ChannelID); err != nil {
			return nil, ErrDevice.SetMsg(err.Error())
		}
	}

	if in.URL != "" {
		svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(c.Request.Context(), sms.DefaultMediaServerID)
		if err != nil {
			return nil, err
		}

		img, err := a.uc.SMSAPI.smsCore.GetSnapshot(svr, sms.GetSnapRequest{
			GetSnapRequest: zlm.GetSnapRequest{
				URL:        in.URL,
				TimeoutSec: 10,
				ExpireSec:  28800,
			},
			Stream: channelID,
		})
		if err != nil {
			slog.ErrorContext(c.Request.Context(), "get snapshot", "err", err)
			// return nil, reason.ErrBadRequest.Msg(err.Error())
		} else {
			if hook.MD5FromBytes(img) != "" {
				if err := writeCover(a.uc.Conf.ConfigDir, channelID, img); err != nil {
					slog.ErrorContext(c.Request.Context(), "write cover", "err", err)
				}
			}
		}
	}

	return gin.H{"link": fmt.Sprintf("%s/channels/%s/snapshot?token=%s", prefix, channelID, token)}, nil
}

func (a IPCAPI) addZone(c *gin.Context, in *ipc.AddZoneInput) (gin.H, error) {
	channelID := c.Param("id")
	if len(in.Labels) == 0 {
		in.Labels = []string{"person", "car", "cat", "dog"}
	}
	zones, err := a.ipc.AddZone(c.Request.Context(), in, channelID)
	return gin.H{"items": zones}, err
}

func (a IPCAPI) getZones(c *gin.Context, _ *struct{}) (any, error) {
	channelID := c.Param("id")
	return a.ipc.GetZones(c.Request.Context(), channelID)
}

func (a IPCAPI) getSnapshot(c *gin.Context) {
	channelID := c.Param("id")
	body, err := readCover(a.uc.Conf.ConfigDir, channelID)
	if err != nil {
		web.Fail(c, reason.ErrNotFound.SetMsg(err.Error()))
		return
	}
	c.Data(200, "image/jpeg", body)
}

func (a IPCAPI) discover(c *gin.Context) {
	p := a.ipc.GetProtocol(ipc.TypeOnvif)
	onvifAdapter, ok := p.(*onvifadapter.Adapter)
	if !ok {
		web.Fail(c, reason.ErrNotFound.SetMsg("不支持的协议"))
		return
	}

	se := web.NewSSE(64, time.Minute)
	go func() {
		defer func() {
			se.Publish(web.Event{
				ID:    uuid.NewString(),
				Event: "end",
			})
			se.Close()
		}()
		w := IOWriter{fn: func(b []byte) (int, error) {
			se.Publish(web.Event{
				ID:    uuid.NewString(),
				Event: "discover",
				Data:  b,
			})
			return len(b), nil
		}}
		if err := onvifAdapter.Discover(c.Request.Context(), w); err != nil {
			slog.ErrorContext(c.Request.Context(), "discover", "err", err)
		}
	}()
	se.ServeHTTP(c.Writer, c.Request)
}

type IOWriter struct {
	fn func(b []byte) (int, error)
}

func (w IOWriter) Write(b []byte) (int, error) {
	return w.fn(b)
}

var (
	ErrAIGlobalDisabled    = reason.NewError("ErrAIGlobalDisabled", "AI 功能已在全局配置中禁用")
	ErrAIServiceNotReady   = reason.NewError("ErrAIServiceNotReady", "AI 服务未初始化或连接失败")
	ErrChannelNotSupported = reason.NewError("ErrChannelNotSupported", "不支持的通道类型")
)

// enableAI 启用指定通道的 AI 检测功能，需要先确保全局 AI 服务已启用且连接正常
func (a IPCAPI) enableAI(c *gin.Context, _ *struct{}) (gin.H, error) {
	channelID := c.Param("id")
	ctx := c.Request.Context()

	// 检查全局 AI 配置
	if a.uc.Conf.Server.AI.Disabled {
		return nil, ErrAIGlobalDisabled
	}
	if a.uc.AIWebhookAPI.ai == nil {
		return nil, ErrAIServiceNotReady
	}

	// 更新数据库中的 AI 启用状态
	channel, err := a.ipc.SetAIEnabled(ctx, channelID, true)
	if err != nil {
		return nil, err
	}

	// 构建 RTSP 地址
	rtspURL, err := a.buildRTSPURL(ctx, channelID)
	if err != nil {
		return nil, err
	}

	// 启动 AI 检测任务
	resp, err := a.uc.AIWebhookAPI.StartAIDetection(ctx, channel, rtspURL)
	if err != nil {
		slog.ErrorContext(ctx, "start camera AI", "err", err)
		return nil, reason.ErrUsedLogic.SetMsg("启动 AI 检测失败: " + err.Error())
	}

	return gin.H{
		"enabled":       true,
		"message":       resp.GetMessage(),
		"source_width":  resp.GetSourceWidth(),
		"source_height": resp.GetSourceHeight(),
		"source_fps":    resp.GetSourceFps(),
	}, nil
}

// disableAI 禁用指定通道的 AI 检测功能，会同时停止正在运行的检测任务
func (a IPCAPI) disableAI(c *gin.Context, _ *struct{}) (gin.H, error) {
	channelID := c.Param("id")
	ctx := c.Request.Context()

	// 检查全局 AI 配置
	if a.uc.Conf.Server.AI.Disabled {
		return nil, ErrAIGlobalDisabled
	}
	if a.uc.AIWebhookAPI.ai == nil {
		return nil, ErrAIServiceNotReady
	}

	// 更新数据库中的 AI 启用状态
	if _, err := a.ipc.SetAIEnabled(ctx, channelID, false); err != nil {
		return nil, err
	}

	// 停止 AI 检测任务
	if err := a.uc.AIWebhookAPI.StopAIDetection(ctx, channelID); err != nil {
		slog.ErrorContext(ctx, "stop camera AI", "err", err)
	}

	return gin.H{
		"enabled": false,
		"message": "AI 检测已停止",
	}, nil
}

// buildRTSPURL 根据通道类型构建对应的 RTSP 播放地址
func (a IPCAPI) buildRTSPURL(ctx context.Context, channelID string) (string, error) {
	svr, err := a.uc.SMSAPI.smsCore.GetMediaServer(ctx, sms.DefaultMediaServerID)
	if err != nil {
		return "", err
	}

	var app, stream string

	if bz.IsGB28181(channelID) {
		app = "rtp"
		stream = channelID
	} else if bz.IsOnvif(channelID) {
		app = "live"
		stream = channelID
	} else if bz.IsRTSP(channelID) || bz.IsRTMP(channelID) {
		// 从 Channel 获取流信息
		ch, err := a.ipc.GetChannel(ctx, channelID)
		if err != nil {
			return "", err
		}
		app = ch.App
		if app == "" {
			app = "live"
		}
		stream = ch.Stream
	} else {
		return "", ErrChannelNotSupported
	}

	return fmt.Sprintf("rtsp://%s:%d/%s/%s", "127.0.0.1", svr.Ports.RTSP, app, stream), nil
}

// setRecordModeInput 设置录像模式请求参数
type setRecordModeInput struct {
	// 录像模式：always-一直录制，ai-按AI触发录制，none-不录制
	Mode string `json:"mode" binding:"required,oneof=always ai none"`
}

// setRecordMode 设置通道的录像模式，支持三种模式：always(一直录制)、ai(AI触发录制)、none(不录制)
// always 和 ai 都会启用录制
func (a IPCAPI) setRecordMode(c *gin.Context, in *setRecordModeInput) (gin.H, error) {
	channelID := c.Param("id")
	ctx := c.Request.Context()

	// 更新通道的录像模式
	channel, err := a.ipc.SetRecordMode(ctx, channelID, in.Mode)
	if err != nil {
		return nil, err
	}

	// 根据录像模式控制 ZLM 录制：
	// - always/ai: 如果流在线则启动录制
	// - none: 停止录制
	if channel.Ext.IsNoneRecord() {
		// none 模式：停止录制
		if err := a.recordingCore.StopRecording(ctx, channel.GetApp(), channel.GetStream()); err != nil {
			slog.WarnContext(ctx, "停止录制失败", "channel", channelID, "err", err)
		}
	} else {
		// always/ai 模式：如果流在线则启动录制
		if channel.IsOnline {
			if err := a.recordingCore.StartRecording(ctx, channel.Type, channel.GetApp(), channel.GetStream()); err != nil {
				slog.WarnContext(ctx, "启动录制失败", "channel", channelID, "err", err)
			}
		}
	}

	return gin.H{
		"id":          channel.ID,
		"record_mode": channel.Ext.GetRecordMode(),
	}, nil
}
