// Code generated by godddx, DO AVOID EDIT.
package api

import (
	"github.com/gin-gonic/gin"
	"github.com/gowvp/owl/internal/core/proxy"
	"github.com/gowvp/owl/internal/core/proxy/store/proxydb"
	"github.com/ixugo/goddd/domain/uniqueid"
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/web"
	"gorm.io/gorm"
)

type ProxyAPI struct {
	proxyCore *proxy.Core
}

func NewProxyCore(db *gorm.DB, uni uniqueid.Core) *proxy.Core {
	return proxy.NewCore(proxydb.NewDB(db).AutoMigrate(orm.GetEnabledAutoMigrate()), uni)
}

func NewProxyAPI(proxyCore *proxy.Core) ProxyAPI {
	return ProxyAPI{proxyCore: proxyCore}
}

// streamProxyIDInput 拉流代理 ID 路径参数
type streamProxyIDInput struct {
	ID string `uri:"id" binding:"required"`
}

// updateStreamProxyInput 更新拉流代理的请求参数（路径 ID + 请求体）
type updateStreamProxyInput struct {
	ID string `uri:"id" binding:"required"`
	proxy.EditStreamProxyInput
}

func registerProxy(g gin.IRouter, api ProxyAPI, handler ...gin.HandlerFunc) {
	{
		group := g.Group("/stream_proxys", handler...)
		group.GET("", web.WrapH(api.listStreamProxys))
		group.GET("/:id", web.WrapH(api.getStreamProxy))
		group.PUT("/:id", web.WrapH(api.updateStreamProxy))
		group.POST("", web.WrapH(api.createStreamProxy))
		group.DELETE("/:id", web.WrapH(api.deleteStreamProxy))
	}
}

// >>> streamProxy >>>>>>>>>>>>>>>>>>>>

func (a ProxyAPI) listStreamProxys(c *gin.Context, in *proxy.FindStreamProxyInput) (any, error) {
	items, total, err := a.proxyCore.ListStreamProxys(c.Request.Context(), in)
	return gin.H{"items": items, "total": total}, err
}

func (a ProxyAPI) getStreamProxy(c *gin.Context, in *streamProxyIDInput) (any, error) {
	return a.proxyCore.GetStreamProxy(c.Request.Context(), in.ID)
}

func (a ProxyAPI) updateStreamProxy(c *gin.Context, in *updateStreamProxyInput) (any, error) {
	return a.proxyCore.UpdateStreamProxy(c.Request.Context(), &in.EditStreamProxyInput, in.ID)
}

func (a ProxyAPI) createStreamProxy(c *gin.Context, in *proxy.AddStreamProxyInput) (any, error) {
	return a.proxyCore.CreateStreamProxy(c.Request.Context(), in)
}

func (a ProxyAPI) deleteStreamProxy(c *gin.Context, in *streamProxyIDInput) (any, error) {
	return a.proxyCore.DeleteStreamProxy(c.Request.Context(), in.ID)
}
