// Code generated by godddx, DO AVOID EDIT.
package ipcdb

import (
	"context"

	"github.com/gowvp/owl/internal/core/ipc"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ ipc.ChannelStorer = Channel{}

// Channel Related business namespaces
type Channel DB

// BatchEdit implements ipc.ChannelStorer.
func (d Channel) BatchEdit(ctx context.Context, column string, value any, args ...orm.QueryOption) error {
	if len(args) == 0 {
		panic("没有查询条件")
	}
	db := d.db.WithContext(ctx).Model(new(ipc.Channel))
	for _, fn := range args {
		fn(db)
	}
	return db.UpdateColumn(column, value).Error
}

// NewChannel instance object
func NewChannel(db *gorm.DB) Channel {
	return Channel{db: db}
}

// List implements ipc.ChannelStorer.
func (d Channel) List(ctx context.Context, bs *[]*ipc.Channel, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements ipc.ChannelStorer.
func (d Channel) Get(ctx context.Context, model *ipc.Channel, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Create implements ipc.ChannelStorer.
func (d Channel) Create(ctx context.Context, model *ipc.Channel) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update implements ipc.ChannelStorer.
func (d Channel) Update(ctx context.Context, model *ipc.Channel, changeFn func(*ipc.Channel) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithContext2(ctx, d.db, model, changeFn, opts...)
}

// EditGB28181Config 直接更新 GB28181 上报的字段（name/is_online/ptztype/ext），跳过 SELECT FOR UPDATE，因为调用方已持有 existing 对象。
func (d Channel) EditGB28181Config(ctx context.Context, model *ipc.Channel) error {
	return d.db.WithContext(ctx).
		Model(model).
		Select("name", "is_online", "ptztype", "ext").
		Updates(model).Error
}

// Delete implements ipc.ChannelStorer.
func (d Channel) Delete(ctx context.Context, model *ipc.Channel, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

func (d Channel) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

func (d Channel) UpdateWithSession(tx *gorm.DB, model *ipc.Channel, changeFn func(b *ipc.Channel) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
