// Code generated by godddx, DO AVOID EDIT.
package ipcdb

import (
	"github.com/gowvp/owl/internal/core/ipc"
	"gorm.io/gorm"
)

var _ ipc.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db      *gorm.DB
	history *ipc.DeviceHistoryStore
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

func NewDBWithHistory(db *gorm.DB, cfg ipc.DeviceHistoryConfig) DB {
	return DB{db: db, history: ipc.NewDeviceHistoryStore(db, cfg, false)}
}

// Device Get business instance
func (d DB) Device() ipc.DeviceStorer {
	return Device(d)
}

// Channel Get business instance
func (d DB) Channel() ipc.ChannelStorer {
	return Channel(d)
}

func (d DB) DeviceHistory() *ipc.DeviceHistoryStore {
	if d.history != nil {
		return d.history
	}
	return ipc.NewDeviceHistoryStore(d.db, ipc.DeviceHistoryConfig{}, false)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(ipc.Device),
		new(ipc.Channel),
	); err != nil {
		panic(err)
	}
	if d.history == nil {
		d.history = ipc.NewDeviceHistoryStore(d.db, ipc.DeviceHistoryConfig{}, true)
	} else if err := d.db.AutoMigrate(new(ipc.DeviceHistoryRecord)); err != nil {
		panic(err)
	}
	return d
}
