// Code generated by godddx, DO AVOID EDIT.
package ipcdb

import (
	"context"

	"github.com/gowvp/owl/internal/core/ipc"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ ipc.DeviceStorer = Device{}

// Device Related business namespaces
type Device DB

// NewDevice instance object
func NewDevice(db *gorm.DB) Device {
	return Device{db: db}
}

// List implements ipc.DeviceStorer.
func (d Device) List(ctx context.Context, bs *[]*ipc.Device, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements ipc.DeviceStorer.
func (d Device) Get(ctx context.Context, model *ipc.Device, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Create implements ipc.DeviceStorer.
func (d Device) Create(ctx context.Context, model *ipc.Device) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update implements ipc.DeviceStorer.
func (d Device) Update(ctx context.Context, model *ipc.Device, changeFn func(*ipc.Device) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithContext2(ctx, d.db, model, changeFn, opts...)
}

// Delete implements ipc.DeviceStorer.
func (d Device) Delete(ctx context.Context, model *ipc.Device, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

func (d Device) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

func (d Device) UpdateWithSession(tx *gorm.DB, model *ipc.Device, changeFn func(b *ipc.Device) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
