// Code generated by godddx, DO AVOID EDIT.
package eventcache

import (
	"context"
	"fmt"

	"github.com/gowvp/owl/internal/core/event"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

// 若不需要实现缓存，可以注释
var _ event.EventStorer = (*Event)(nil)

type Event Cache

func (c *Event) cacheKey(key any) string {
	return fmt.Sprintf("EVENT:%v", key)
}

// List implements event.EventStorer.
func (c *Event) List(ctx context.Context, bs *[]*event.Event, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return c.store.Event().List(ctx, bs, page, opts...)
}

// Get implements event.EventStorer.
// 注意: 若想走缓存，则 model 的 CacheKey 必须实现且必须存在值
// 当 CacheKey 为 id 且出现 orm.Where("id=?",id) 时，查询条件会变成
// SELECT * FROM `users` WHERE `id` = 1 AND `users`.`id` = 1
// 两个值一样则不会受到影响
func (c *Event) Get(ctx context.Context, model *event.Event, opts ...orm.QueryOption) error {
	if model.CacheKey() != "" {
		if err := c.event.Get(ctx, c.cacheKey(model.CacheKey()), model); err == nil {
			return nil
		}
	}
	if err := c.store.Event().Get(ctx, model, opts...); err != nil {
		return err
	}
	c.event.SetNX(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Create implements event.EventStorer.
func (c *Event) Create(ctx context.Context, model *event.Event) error {
	if err := c.store.Event().Create(ctx, model); err != nil {
		return err
	}
	c.event.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Update implements event.EventStorer.
func (c *Event) Update(ctx context.Context, model *event.Event, changeFn func(*event.Event), opts ...orm.QueryOption) error {
	if err := c.store.Event().Update(ctx, model, changeFn, opts...); err != nil {
		return err
	}
	c.event.Set(ctx, c.cacheKey(model.CacheKey()), model)
	return nil
}

// Delete implements event.EventStorer.
func (c *Event) Delete(ctx context.Context, model *event.Event, opts ...orm.QueryOption) error {
	if err := c.store.Event().Delete(ctx, model, opts...); err != nil {
		return err
	}
	c.event.Del(ctx, c.cacheKey(model.CacheKey()))
	return nil
}

// Count implements event.EventStorer.
func (c *Event) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return c.store.Event().Count(ctx, opts...)
}

// Session 事务组合
func (c *Event) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	// return c.store.Event().Session(ctx, changeFns...)
	return nil
}

// UpdateWithSession 修改事务
func (c *Event) UpdateWithSession(tx *gorm.DB, model *event.Event, changeFn func(b *event.Event) error, opts ...orm.QueryOption) error {
	//	if err := c.store.Event().UpdateWithSession(ctx,model, changeFn,opts...);err!=nil{
	// return err
	//	}
	//	c.event.Set(ctx, c.cacheKey(model.CacheKey() ),  model)
	return nil
}
