// Code generated by godddx, DO AVOID EDIT.
package recordingdb

import (
	"context"

	"github.com/gowvp/owl/internal/core/recording"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ recording.RecordingStorer = Recording{}

// Recording Related business namespaces
type Recording DB

// NewRecording instance object
func NewRecording(db *gorm.DB) Recording {
	return Recording{db: db}
}

// List implements recording.RecordingStorer.
func (d Recording) List(ctx context.Context, bs *[]*recording.Recording, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements recording.RecordingStorer.
func (d Recording) Get(ctx context.Context, model *recording.Recording, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Create implements recording.RecordingStorer.
func (d Recording) Create(ctx context.Context, model *recording.Recording) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Update implements recording.RecordingStorer.
func (d Recording) Update(ctx context.Context, model *recording.Recording, changeFn func(*recording.Recording), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Delete implements recording.RecordingStorer.
func (d Recording) Delete(ctx context.Context, model *recording.Recording, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

// Count implements recording.RecordingStorer.
func (d Recording) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return orm.CountWithContext[recording.Recording](ctx, d.db, opts...)
}

// Session 事务组合
func (d Recording) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// UpdateWithSession 修改事务
func (d Recording) UpdateWithSession(tx *gorm.DB, model *recording.Recording, changeFn func(b *recording.Recording) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
