// Code generated by godddx, DO AVOID EDIT.
package ipc

import (
	"github.com/ixugo/goddd/pkg/web"
)

type FindDeviceInput struct {
	web.PagerFilter
	Key string `form:"key"`
	// DeviceID string `form:"device_id"` // 20 位国标编号
	// Name     string `form:"name"`      // 设备名称
	// ID       string `form:"id"`
	// Transport    string    `form:"Transport"`   // 传输协议(TCP/UDP)
	// StreamMode   string    `form:"stream_mode"` // 数据传输模式(UDP/TCP_PASSIVE,TCP_ACTIVE)
	// IP           string    `form:"ip"`
	// Port         int       `form:"port"`
	// IsOnline     bool      `form:"is_online"`
	// RegisteredAt orm.Time  `form:"registered_at"` // 注册时间
	// KeepaliveAt  orm.Time  `form:"keepalive_at"`  // 心跳时间
	// Keepalives   int       `form:"keepalives"`    // 心跳间隔
	// Expires      int       `form:"expires"`       // 注册有效期
	// Channels     int       `form:"channels"`      // 通道数量
	// Ext          DeviceExt `form:"ext"`           // 设备属性
}

type EditDeviceInput struct {
	DeviceID   string `json:"device_id"`   // 20 位国标编号
	Name       string `json:"name"`        // 设备名称
	Password   string `json:"password"`    // 注册密码
	StreamMode int    `json:"stream_mode"` // 数据传输模式

	Username string `json:"username"` // 用户名
	IP       string `json:"ip"`       // ip
	Port     int    `json:"port"`     // port
	// GBVersion 手动指定 GB/T 28181 协议版本；支持 1.0/1.1/2.0/3.0 和历史年份值。
	// nil 表示不修改，空字符串表示清除手动覆盖并恢复自动协商。
	GBVersion *string `json:"gb_version,omitempty"`

	// IP           string    `json:"ip"`
	// Port         int       `json:"port"`
	// IsOnline     bool      `json:"is_online"`
	// RegisteredAt orm.Time  `json:"registered_at"` // 注册时间
	// KeepaliveAt  orm.Time  `json:"keepalive_at"`  // 心跳时间
	// Keepalives   int       `json:"keepalives"`    // 心跳间隔
	// Expires      int       `json:"expires"`       // 注册有效期
	// Channels     int       `json:"channels"`      // 通道数量
	// Ext          DeviceExt `json:"ext"`           // 设备属性
}

// 目前仅应用于 onvif 添加
type AddDeviceInput struct {
	DeviceID string `json:"device_id"` // 20 位国标编号
	// onvif
	Username string `json:"username"` // 用户名
	IP       string `json:"ip"`       // ip
	Port     int    `json:"port"`     // port
	// 通用
	Name     string `json:"name"`     // 设备名称
	Password string `json:"password"` // 注册密码

	Type string `json:"type"` // 设备类型(ONVIF/GB28181)

	// Addr     string `json:"addr"`     // 地址(ip:port)

	// Transport    string    `json:"transport"`   // 传输协议(TCP/UDP)
	// StreamMode   string    `json:"stream_mode"` // 数据传输模式(UDP/TCP_PASSIVE,TCP_ACTIVE)
	// IP           string    `json:"ip"`
	// Port         int       `json:"port"`
	// IsOnline     bool      `json:"is_online"`
	// RegisteredAt orm.Time  `json:"registered_at"` // 注册时间
	// KeepaliveAt  orm.Time  `json:"keepalive_at"`  // 心跳时间
	// Keepalives   int       `json:"keepalives"`    // 心跳间隔
	// Expires      int       `json:"expires"`       // 注册有效期
	// Channels     int       `json:"channels"`      // 通道数量
	// Ext          DeviceExt `json:"ext"`           // 设备属性
}
