// Code generated by godddx, DO AVOID EDIT.
package ipc

import (
	"context"
	"fmt"
	"log/slog"
	"strconv"
	"strings"
	"time"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/ixugo/goddd/pkg/web"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
)

// DeviceStorer Instantiation interface
type DeviceStorer interface {
	List(context.Context, *[]*Device, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Device, ...orm.QueryOption) error
	Create(context.Context, *Device) error
	Update(context.Context, *Device, func(*Device) error, ...orm.QueryOption) error
	Delete(context.Context, *Device, ...orm.QueryOption) error

	Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error
}

func (c Core) FindChannelsForDevice(ctx context.Context, in *FindDeviceInput) ([]*Device, int64, error) {
	items := make([]*Device, 0, in.Limit())

	query := orm.NewQuery(3)
	query.OrderBy("created_at DESC")

	total, err := c.store.Device().List(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`Find err[%s]`, err.Error())
	}

	for _, item := range items {
		// 限制查询通道数量
		const size = 5
		item.Children = make([]*Channel, 0, size)
		query := orm.NewQuery(2).OrderBy("created_at DESC").Where("did=?", item.ID)
		_, err := c.store.Channel().List(ctx, &item.Children, web.PagerFilter{Size: size}, query.Encode()...)
		if err != nil {
			continue
		}

		for _, ch := range item.Children {
			if !item.IsOnline {
				ch.IsOnline = false
				ch.IsPlaying = false
			}
		}
	}

	return items, total, nil
}

// FindDevice Paginated search
func (c Core) FindDevice(ctx context.Context, in *FindDeviceInput) ([]*Device, int64, error) {
	items := make([]*Device, 0)

	query := orm.NewQuery(3)
	query.OrderBy("created_at DESC")
	if in.Key != "" {
		query.Where("name LIKE ? OR device_id like ? OR id=?", "%"+in.Key+"%", "%"+in.Key+"%", in.Key)
	}
	if in.Type != "" {
		query.Where("type = ?", strings.ToUpper(strings.TrimSpace(in.Type)))
	}
	if in.IsOnline == "true" || in.IsOnline == "false" {
		isOnline, _ := strconv.ParseBool(in.IsOnline)
		query.Where("is_online = ?", isOnline)
	}

	total, err := c.store.Device().List(ctx, &items, in, query.Encode()...)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`Find err[%s]`, err.Error())
	}
	return items, total, nil
}

// ListDevices 是升级后的命名入口，保留 FindDevice 以兼容现有调用。
func (c Core) ListDevices(ctx context.Context, in *FindDeviceInput) ([]*Device, int64, error) {
	return c.FindDevice(ctx, in)
}

// GetDevice Query a single object
func (c Core) GetDevice(ctx context.Context, id string) (*Device, error) {
	return c.resolveDevice(ctx, id)
}

func (c Core) GetDeviceByDeviceID(ctx context.Context, deviceID string) (*Device, error) {
	var out Device
	if err := c.store.Device().Get(ctx, &out, orm.Where("device_id=?", deviceID)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return &out, nil
}

// AddDevice Insert into database
func (c Core) AddDevice(ctx context.Context, in *AddDeviceInput) (*Device, error) {
	if strings.EqualFold(strings.TrimSpace(in.Type), TypeGB28181) && !validGBRTPStreamMode(in.StreamMode) {
		return nil, reason.ErrBadRequest.SetMsg(fmt.Sprintf("invalid RTP stream mode: %d", in.StreamMode))
	}
	var out Device
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}

	// 协议验证（通过接口调用）
	if protocol, ok := c.protocols[out.GetType()]; ok {
		if err := protocol.ValidateDevice(ctx, &out); err != nil {
			return nil, reason.ErrBadRequest.SetMsg(err.Error())
		}
	}

	out.ID = GenerateDID(&out, c.uniqueID)
	if out.IsOnvif() {
		out.DeviceID = out.ID
	} else {
		out.Username = out.DeviceID
	}

	if err := out.Check(); err != nil {
		return nil, reason.ErrBadRequest.SetMsg(err.Error())
	}

	// 持久化到数据库
	if err := c.store.Device().Create(ctx, &out); err != nil {
		if orm.IsDuplicatedKey(err) {
			return nil, reason.ErrDB.SetMsg("国标 ID 重复，请勿重复添加")
		}
		return nil, reason.ErrDB.Withf(`Add err[%s]`, err.Error())
	}

	// 初始化协议连接（失败不影响设备添加）
	if protocol, ok := c.protocols[out.GetType()]; ok {
		if err := protocol.InitDevice(ctx, &out); err != nil {
			return nil, reason.ErrBadRequest.SetMsg(err.Error())
		}
	}

	return &out, nil
}

// EditDevice Update object information
func (c Core) EditDevice(ctx context.Context, in *EditDeviceInput, id string) (*Device, error) {
	manualVersion := ""
	if in.GBVersion != nil {
		var ok bool
		manualVersion, ok = normalizeManualGBVersion(*in.GBVersion)
		if !ok {
			return nil, reason.ErrBadRequest.SetMsg("gb_version 仅支持 1.0/1.1/2.0/3.0")
		}
	}

	dev, err := c.resolveDevice(ctx, id)
	if err != nil {
		return nil, err
	}
	if dev.IsGB28181() && !validGBRTPStreamMode(in.StreamMode) {
		return nil, reason.ErrBadRequest.SetMsg(fmt.Sprintf("invalid RTP stream mode: %d", in.StreamMode))
	}
	if dev.IsGB28181() && in.DeviceID != dev.DeviceID {
		return nil, reason.ErrBadRequest.SetMsg("GB28181 device_id 是协议身份，不能原地修改，请删除后重新添加")
	}
	var editCoordinator DeviceEditCoordinator
	if protocol, ok := c.protocols[dev.GetType()]; ok {
		editCoordinator, _ = protocol.(DeviceEditCoordinator)
		if editCoordinator != nil {
			if unlock := editCoordinator.LockDeviceEdit(dev); unlock != nil {
				defer unlock()
			}
		}
	}

	var before Device
	var out Device
	if err := c.store.Device().Update(ctx, &out, func(b *Device) error {
		before = *b
		previousPassword := b.Password
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
		if in.Password == nil {
			b.Password = previousPassword
		} else {
			b.Password = *in.Password
		}
		if in.GBVersion != nil {
			applyManualGBVersion(&b.Ext, manualVersion)
		}
		if in.GBDisabledCapabilities != nil {
			if b.GetType() != TypeGB28181 {
				return reason.ErrBadRequest.SetMsg("gb_disabled_capabilities 仅适用于 GB28181 设备")
			}
			b.Ext.GBDisabledCapabilities = append([]string(nil), (*in.GBDisabledCapabilities)...)
		}

		protocol, ok := c.protocols[b.GetType()]
		if ok {
			if err := protocol.ValidateDevice(ctx, b); err != nil {
				slog.WarnContext(ctx, "验证协议失败", "err", err, "device_id", b.ID)
				return err
			}
		}

		return nil
	}, orm.Where("id=?", dev.ID)); err != nil {
		return nil, reason.ErrDB.Withf(`Edit err[%s] id[%s]`, err.Error(), dev.ID)
	}
	if editCoordinator != nil {
		if err := editCoordinator.DeviceEdited(ctx, &before, &out); err != nil {
			return nil, reason.ErrDB.Withf(`Finalize edit err[%s] id[%s]`, err.Error(), dev.ID)
		}
	}

	protocol, ok := c.protocols[out.GetType()]
	if ok {
		if err := protocol.InitDevice(ctx, &out); err != nil {
			slog.WarnContext(ctx, "初始化协议失败", "err", err, "device_id", out.ID)
		}
	}
	return &out, nil
}

func validGBRTPStreamMode(streamMode int) bool {
	return streamMode >= 0 && streamMode <= 2
}

func normalizeManualGBVersion(value string) (string, bool) {
	switch strings.TrimSpace(value) {
	case "":
		return "", true
	case "1.0", "2011":
		return "1.0", true
	case "1.1", "2014", "2011-supplement-2014":
		return "1.1", true
	case "2.0", "2016":
		return "2.0", true
	case "3.0", "2022":
		return "3.0", true
	default:
		return "", false
	}
}

func applyManualGBVersion(ext *DeviceExt, version string) {
	ext.GBManualVersion = version
	ext.GBVersionUpdatedAt = time.Now().Unix()
	if version != "" {
		ext.GBEffectiveVersion = version
		ext.GBVersionSource = "manual"
		ext.GBVersion = gbVersionYear(version)
		return
	}

	if declared, ok := normalizeManualGBVersion(ext.GBDeclaredVersion); ok && declared != "" {
		ext.GBEffectiveVersion = declared
		ext.GBVersionSource = "header"
		ext.GBVersion = gbVersionYear(declared)
		return
	}

	ext.GBEffectiveVersion = ""
	ext.GBVersionSource = ""
	ext.GBVersion = ""
}

func gbVersionYear(version string) string {
	switch version {
	case "1.0":
		return "2011"
	case "1.1":
		return "2014"
	case "2.0":
		return "2016"
	case "3.0":
		return "2022"
	default:
		return ""
	}
}

// DelDevice Delete object
func (c Core) DelDevice(ctx context.Context, id string) (*Device, error) {
	device, _, err := c.delDevice(ctx, id, false)
	return device, err
}

// DelDeviceWithChannelIDs 在协议删除锁内捕获最终通道集合，供调用方清理通道级外部资源。
func (c Core) DelDeviceWithChannelIDs(ctx context.Context, id string) (*Device, []string, error) {
	return c.delDevice(ctx, id, true)
}

func (c Core) delDevice(ctx context.Context, id string, captureChannelIDs bool) (*Device, []string, error) {
	target, err := c.resolveDevice(ctx, id)
	if err != nil {
		return nil, nil, err
	}
	var channelIDs []string
	if protocol, ok := c.protocols[target.GetType()]; ok {
		if locker, coordinated := protocol.(DeviceDeleteLocker); coordinated {
			if unlock := locker.LockDeviceDelete(target); unlock != nil {
				defer unlock()
			}
		}
		if captureChannelIDs {
			channelIDs, err = c.channelIDsForDevice(ctx, target.ID)
			if err != nil {
				return nil, nil, reason.ErrDB.Withf(`List channels before delete err[%s]`, err.Error())
			}
		}
		if err := protocol.DeleteDevice(ctx, target); err != nil {
			return nil, channelIDs, reason.ErrDB.Withf(`Cleanup device err[%s]`, err.Error())
		}
	} else if captureChannelIDs {
		channelIDs, err = c.channelIDsForDevice(ctx, target.ID)
		if err != nil {
			return nil, nil, reason.ErrDB.Withf(`List channels before delete err[%s]`, err.Error())
		}
	}

	// 传入已解析的完整设备，避免底层删除逻辑依赖数据库对 DELETE RETURNING 的支持。
	dev := *target
	if err := c.store.Device().Delete(ctx, &dev, orm.Where("id=?", target.ID)); err != nil {
		return nil, channelIDs, reason.ErrDB.Withf(`Del err[%s]`, err.Error())
	}

	// 缓存存储会在 Device.Delete 事务内删除通道；保留兜底删除以兼容直接使用数据库存储的调用方。
	if err := c.store.Channel().Session(ctx, func(d *gorm.DB) error {
		return d.Where("did=?", target.ID).Delete(&Channel{}).Error
	}); err != nil {
		return nil, channelIDs, reason.ErrDB.Withf(`DelChannel err[%s]`, err.Error())
	}

	return &dev, channelIDs, nil
}

func (c Core) channelIDsForDevice(ctx context.Context, deviceID string) ([]string, error) {
	const pageSize = 500
	channelIDs := make([]string, 0)
	for page := 1; ; page++ {
		items := make([]*Channel, 0, pageSize)
		query := orm.NewQuery(1).Where("did=?", deviceID).OrderBy("id")
		total, err := c.store.Channel().List(ctx, &items, web.PagerFilter{Page: page, Size: pageSize}, query.Encode()...)
		if err != nil {
			return nil, err
		}
		for _, item := range items {
			if item != nil && strings.TrimSpace(item.ID) != "" {
				channelIDs = append(channelIDs, item.ID)
			}
		}
		if len(items) == 0 || len(channelIDs) >= int(total) || len(items) < pageSize {
			return channelIDs, nil
		}
	}
}

func (c Core) QueryCatalog(ctx context.Context, deviceID string) error {
	device, err := c.GetDevice(ctx, deviceID)
	if err != nil {
		return err
	}
	if err := c.protocols[device.GetType()].QueryCatalog(ctx, device); err != nil {
		return reason.ErrBadRequest.SetMsg(err.Error())
	}
	return nil
}
