// Code generated by godddx, DO AVOID EDIT.
package ipc

import (
	"database/sql/driver"
	"encoding/json"

	"github.com/gowvp/owl/internal/core/bz"
	"github.com/ixugo/goddd/pkg/orm"
)

const (
	TypeGB28181 = "GB28181"
	TypeOnvif   = "ONVIF"
	TypeRTSP    = "RTSP"
	TypeRTMP    = "RTMP"
)

var defaultRecordMode = "always"

func normalizeRecordMode(mode string) string {
	switch mode {
	case "always", "ai", "none":
		return mode
	default:
		return "always"
	}
}

// SetDefaultRecordMode 设置全局默认录像模式（仅用于通道未配置 record_mode 的场景）。
func SetDefaultRecordMode(mode string) {
	defaultRecordMode = normalizeRecordMode(mode)
}

func GetType(stream string) string {
	switch true {
	case bz.IsGB28181(stream):
		return TypeGB28181
	case bz.IsOnvif(stream):
		return TypeOnvif
	case bz.IsRTSP(stream):
		return TypeRTSP
	case bz.IsRTMP(stream):
		return TypeRTMP
	default:
		return ""
	}
}

// DeviceExt domain model
type DeviceExt struct {
	Manufacturer string `json:"manufacturer"` // 生产厂商
	Model        string `json:"model"`        // 型号
	Firmware     string `json:"firmware"`     // 固件版本
	Name         string `json:"name"`         // 设备名
	GBVersion    string `json:"gb_version"`   // GB版本（兼容历史年份值）
	// GBDeclaredVersion 是设备通过 X-GB-Ver 声明的版本号。
	GBDeclaredVersion string `json:"gb_declared_version,omitempty"`
	// GBEffectiveVersion 是平台下行实际使用的版本号。
	GBEffectiveVersion string `json:"gb_effective_version,omitempty"`
	// GBManualVersion 非空时覆盖自动协商；值为空表示恢复自动协商。
	GBManualVersion string `json:"gb_manual_version,omitempty"`
	// GBVersionSource 记录 effective version 的来源：manual/header/legacy/default。
	GBVersionSource string `json:"gb_version_source,omitempty"`
	// GBVersionUpdatedAt 是最近一次版本协商时间（Unix 秒）。
	GBVersionUpdatedAt         int64    `json:"gb_version_updated_at,omitempty"`
	GBVersionCapabilities      []string `json:"gb_version_capabilities,omitempty"`
	GBLastUnsupportedCommand   string   `json:"gb_last_unsupported_command,omitempty"`
	GBLastUnsupportedVersion   string   `json:"gb_last_unsupported_version,omitempty"`
	GBLastUnsupportedUpdatedAt int64    `json:"gb_last_unsupported_updated_at,omitempty"`
	Zones                      []Zone   `json:"zones"`        // 区域
	EnabledAI                  bool     `json:"enabled_ai"`   // 是否启用 AI
	PTZVerified                bool     `json:"ptz_verified"` // 是否已通过实际命令验证支持 PTZ
	// GBAppendixA4 保存 GB/T 28181-2022 附录 A.4 扩展对象最新快照（结构化落库）。
	GBAppendixA4 []GBAppendixA4Object `json:"gb_appendix_a4"`
	// GBCatalog 保存 GB/T 28181 目录项扩展和原始 XML，兼容 2014 及厂商私有字段。
	GBCatalog *GBCatalogExt `json:"gb_catalog,omitempty"`

	// 空串表示 always
	RecordMode string `json:"record_mode"` // 录像模式, 一直录制:always, 按AI触发:ai, 不录制:none
}

// GBCatalogExt 是通道或目录节点的 GB/T 28181 目录扩展快照。
// 使用 ext JSON 持久化，避免为可选协议字段增加大量数据库列。
type GBCatalogExt struct {
	Kind            string  `json:"kind,omitempty"`
	Owner           string  `json:"owner,omitempty"`
	CivilCode       string  `json:"civil_code,omitempty"`
	Block           string  `json:"block,omitempty"`
	Address         string  `json:"address,omitempty"`
	Parental        int     `json:"parental,omitempty"`
	ParentID        string  `json:"parent_id,omitempty"`
	SafetyWay       int     `json:"safety_way,omitempty"`
	RegisterWay     int     `json:"register_way,omitempty"`
	CertNum         string  `json:"cert_num,omitempty"`
	Certifiable     int     `json:"certifiable,omitempty"`
	ErrCode         int     `json:"err_code,omitempty"`
	EndTime         string  `json:"end_time,omitempty"`
	Secrecy         int     `json:"secrecy,omitempty"`
	IPAddress       string  `json:"ip_address,omitempty"`
	Port            int     `json:"port,omitempty"`
	Password        string  `json:"password,omitempty"`
	Status          string  `json:"status,omitempty"`
	Longitude       float64 `json:"longitude,omitempty"`
	Latitude        float64 `json:"latitude,omitempty"`
	PTZType         int     `json:"ptz_type,omitempty"`
	PositionType    int     `json:"position_type,omitempty"`
	RoomType        int     `json:"room_type,omitempty"`
	UseType         int     `json:"use_type,omitempty"`
	SupplyLightType int     `json:"supply_light_type,omitempty"`
	DirectionType   int     `json:"direction_type,omitempty"`
	Resolution      string  `json:"resolution,omitempty"`
	BusinessGroupID string  `json:"business_group_id,omitempty"`
	RawXML          string  `json:"raw_xml,omitempty"`
	InfoRawXML      string  `json:"info_raw_xml,omitempty"`
}

// GBAppendixA4Object 是附录 A.4 扩展对象的统一结构化模型。
// 该模型同时用于：
// 1) 设备 ext 字段持久化；
// 2) GB 查询接口返回。
type GBAppendixA4Object struct {
	Type      string            `json:"type"`                 // 扩展对象名称（如 doorType、alarmType）
	CmdType   string            `json:"cmd_type,omitempty"`   // 来源命令类型（如 DeviceStatus/Alarm）
	Path      string            `json:"path,omitempty"`       // 在 XML 中的路径
	Fields    map[string]string `json:"fields,omitempty"`     // 首层结构化字段
	RawXML    string            `json:"raw_xml,omitempty"`    // 原始 XML 片段，便于兼容厂商私有字段
	UpdatedAt int64             `json:"updated_at,omitempty"` // 最近更新时间（unix 秒）
}

func (e *DeviceExt) GetRecordMode() string {
	if e.RecordMode == "" {
		return defaultRecordMode
	}
	return normalizeRecordMode(e.RecordMode)
}

func (e *DeviceExt) IsAlwaysRecord() bool {
	return e.GetRecordMode() == "always"
}

func (e *DeviceExt) IsAIRecord() bool {
	return e.GetRecordMode() == "ai"
}

func (e *DeviceExt) IsNoneRecord() bool {
	return e.GetRecordMode() == "none"
}

// Scan implements orm.Scaner.
func (i *DeviceExt) Scan(input any) error {
	return orm.JSONUnmarshal(input, i)
}

func (i DeviceExt) Value() (driver.Value, error) {
	return json.Marshal(i)
}

type Zone struct {
	Name        string    `json:"name"`        // 区域名称
	Coordinates []float32 `json:"coordinates"` // 坐标
	Color       string    `json:"color"`       // 颜色，支持 hex 颜色值，如 #FF0000
	Labels      []string  `json:"labels"`      // 标签
}

// StreamConfig 流配置，用于 RTMP 推流和 RTSP 拉流代理
type StreamConfig struct {
	// RTMP 推流配置
	IsAuthDisabled bool      `json:"is_auth_disabled"`    // 是否禁用推流鉴权
	Session        string    `json:"session,omitempty"`   // 推流鉴权参数（由推流客户端携带）
	PushedAt       *orm.Time `json:"pushed_at"`           // 最后推流时间
	StoppedAt      *orm.Time `json:"stopped_at"`          // 最后停止时间
	MediaServerID  string    `json:"media_server_id"`     // 媒体服务器 ID
	PushAddr       string    `json:"push_addr,omitempty"` // 推流地址（动态生成，不持久化）

	// RTSP 拉流配置
	SourceURL                 string `json:"source_url"`                   // 原始 URL
	Transport                 int    `json:"transport"`                    // 拉流方式 (0:tcp, 1:udp)
	TimeoutS                  int    `json:"timeout_s"`                    // 超时时间
	EnabledAudio              bool   `json:"enabled_audio"`                // 是否启用音频
	EnabledRemoveNoneReader   bool   `json:"enabled_remove_none_reader"`   // 无人观看时删除
	EnabledDisabledNoneReader bool   `json:"enabled_disabled_none_reader"` // 无人观看时禁用
	StreamKey                 string `json:"stream_key"`                   // ZLM 返回的 key
	Enabled                   bool   `json:"enabled"`                      // 是否启用
}

// Scan implements orm.Scanner
func (s *StreamConfig) Scan(input any) error {
	return orm.JSONUnmarshal(input, s)
}

// Value implements driver.Valuer
func (s StreamConfig) Value() (driver.Value, error) {
	return json.Marshal(s)
}
