// Code generated by godddx, DO AVOID EDIT.
package config

import (
	"context"
	"log/slog"

	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/reason"
	"github.com/jinzhu/copier"
)

// ConfigStorer Instantiation interface
type ConfigStorer interface {
	List(context.Context, *[]*Config, orm.Pager, ...orm.QueryOption) (int64, error)
	Get(context.Context, *Config, ...orm.QueryOption) error
	Create(context.Context, *Config) error
	Update(context.Context, *Config, func(*Config), ...orm.QueryOption) error
	Delete(context.Context, *Config, ...orm.QueryOption) error

	FirstOrCreate(*Config) error
}

// ListConfigs Paginated search
func (c Core) ListConfigs(ctx context.Context, in *FindConfigInput) ([]*Config, int64, error) {
	items := make([]*Config, 0)
	total, err := c.store.Config().List(ctx, &items, in)
	if err != nil {
		return nil, 0, reason.ErrDB.Withf(`List err[%s]`, err.Error())
	}
	return items, total, nil
}

// GetConfig Query a single object
func (c Core) GetConfig(ctx context.Context, id int) (*Config, error) {
	var out Config
	if err := c.store.Config().Get(ctx, &out, orm.Where("id=?", id)); err != nil {
		if orm.IsErrRecordNotFound(err) {
			return nil, reason.ErrNotFound.Withf(`Get err[%s]`, err.Error())
		}
		return nil, reason.ErrDB.Withf(`Get err[%s]`, err.Error())
	}
	return &out, nil
}

// CreateConfig Insert into database
func (c Core) CreateConfig(ctx context.Context, in *AddConfigInput) (*Config, error) {
	var out Config
	if err := copier.Copy(&out, in); err != nil {
		slog.ErrorContext(ctx, "Copy", "err", err)
	}
	if err := c.store.Config().Create(ctx, &out); err != nil {
		return nil, reason.ErrDB.Withf(`Create err[%s]`, err.Error())
	}
	return &out, nil
}

// UpdateConfig Update object information
func (c Core) UpdateConfig(ctx context.Context, in *EditConfigInput, id int) (*Config, error) {
	var out Config
	if err := c.store.Config().Update(ctx, &out, func(b *Config) {
		if err := copier.Copy(b, in); err != nil {
			slog.ErrorContext(ctx, "Copy", "err", err)
		}
	}, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Update err[%s]`, err.Error())
	}
	return &out, nil
}

// DeleteConfig Delete object
func (c Core) DeleteConfig(ctx context.Context, id int) (*Config, error) {
	var out Config
	if err := c.store.Config().Delete(ctx, &out, orm.Where("id=?", id)); err != nil {
		return nil, reason.ErrDB.Withf(`Delete err[%s]`, err.Error())
	}
	return &out, nil
}
